[2023-01-04 13:45:53,567] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: populate_crypto_values.get_crypto_values scheduled__2022-09-22T07:00:00+00:00 [queued]>
[2023-01-04 13:45:53,574] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: populate_crypto_values.get_crypto_values scheduled__2022-09-22T07:00:00+00:00 [queued]>
[2023-01-04 13:45:53,575] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2023-01-04 13:45:53,575] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2023-01-04 13:45:53,575] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2023-01-04 13:45:53,588] {taskinstance.py:1377} INFO - Executing <Task(PythonOperator): get_crypto_values> on 2022-09-22 07:00:00+00:00
[2023-01-04 13:45:53,593] {standard_task_runner.py:52} INFO - Started process 31854 to run task
[2023-01-04 13:45:53,598] {standard_task_runner.py:79} INFO - Running: ['airflow', 'tasks', 'run', 'populate_crypto_values', 'get_crypto_values', 'scheduled__2022-09-22T07:00:00+00:00', '--job-id', '690', '--raw', '--subdir', 'DAGS_FOLDER/populate_crypto_values.py', '--cfg-path', '/tmp/tmp1bdofaou', '--error-file', '/tmp/tmpuoxpm08s']
[2023-01-04 13:45:53,599] {standard_task_runner.py:80} INFO - Job 690: Subtask get_crypto_values
[2023-01-04 13:45:53,830] {task_command.py:370} INFO - Running <TaskInstance: populate_crypto_values.get_crypto_values scheduled__2022-09-22T07:00:00+00:00 [running]> on host xuxon-virtual-machine
[2023-01-04 13:45:53,902] {taskinstance.py:1569} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=populate_crypto_values
AIRFLOW_CTX_TASK_ID=get_crypto_values
AIRFLOW_CTX_EXECUTION_DATE=2022-09-22T07:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-09-22T07:00:00+00:00
[2023-01-04 13:45:54,018] {logging_mixin.py:115} INFO - Attempt 1 to get the crypto values has failed. The api status was 429
[2023-01-04 13:45:54,019] {logging_mixin.py:115} INFO - The api response was {"status":{"error_code":429,"error_message":"You've exceeded the Rate Limit. Please visit https://www.coingecko.com/en/api/pricing to subscribe to our API plans for higher rate limits."}}
[2023-01-04 13:46:09,142] {logging_mixin.py:115} INFO - Attempt 2 to get the crypto values has failed. The api status was 429
[2023-01-04 13:46:09,143] {logging_mixin.py:115} INFO - The api response was {"status":{"error_code":429,"error_message":"You've exceeded the Rate Limit. Please visit https://www.coingecko.com/en/api/pricing to subscribe to our API plans for higher rate limits."}}
[2023-01-04 13:46:24,319] {logging_mixin.py:115} INFO - Attempt 3 to get the crypto values has failed. The api status was 429
[2023-01-04 13:46:24,319] {logging_mixin.py:115} INFO - The api response was {"status":{"error_code":429,"error_message":"You've exceeded the Rate Limit. Please visit https://www.coingecko.com/en/api/pricing to subscribe to our API plans for higher rate limits."}}
[2023-01-04 13:46:39,443] {logging_mixin.py:115} INFO - Attempt 4 to get the crypto values has failed. The api status was 429
[2023-01-04 13:46:39,444] {logging_mixin.py:115} INFO - The api response was {"status":{"error_code":429,"error_message":"You've exceeded the Rate Limit. Please visit https://www.coingecko.com/en/api/pricing to subscribe to our API plans for higher rate limits."}}
[2023-01-04 13:46:54,560] {logging_mixin.py:115} INFO - Attempt 5 to get the crypto values has failed. The api status was 429
[2023-01-04 13:46:54,560] {logging_mixin.py:115} INFO - The api response was {"status":{"error_code":429,"error_message":"You've exceeded the Rate Limit. Please visit https://www.coingecko.com/en/api/pricing to subscribe to our API plans for higher rate limits."}}
[2023-01-04 13:47:09,670] {logging_mixin.py:115} INFO - Attempt 6 to get the crypto values has failed. The api status was 429
[2023-01-04 13:47:09,671] {logging_mixin.py:115} INFO - The api response was {"status":{"error_code":429,"error_message":"You've exceeded the Rate Limit. Please visit https://www.coingecko.com/en/api/pricing to subscribe to our API plans for higher rate limits."}}
[2023-01-04 13:47:24,788] {logging_mixin.py:115} INFO - Attempt 7 to get the crypto values has failed. The api status was 429
[2023-01-04 13:47:24,789] {logging_mixin.py:115} INFO - The api response was {"status":{"error_code":429,"error_message":"You've exceeded the Rate Limit. Please visit https://www.coingecko.com/en/api/pricing to subscribe to our API plans for higher rate limits."}}
[2023-01-04 13:47:39,906] {logging_mixin.py:115} INFO - Attempt 8 to get the crypto values has failed. The api status was 429
[2023-01-04 13:47:39,906] {logging_mixin.py:115} INFO - The api response was {"status":{"error_code":429,"error_message":"You've exceeded the Rate Limit. Please visit https://www.coingecko.com/en/api/pricing to subscribe to our API plans for higher rate limits."}}
[2023-01-04 13:47:55,976] {logging_mixin.py:115} INFO - New rows have been added.
[2023-01-04 13:47:55,976] {python.py:173} INFO - Done. Returned value was: None
[2023-01-04 13:47:56,008] {taskinstance.py:1395} INFO - Marking task as SUCCESS. dag_id=populate_crypto_values, task_id=get_crypto_values, execution_date=20220922T070000, start_date=20230104T164553, end_date=20230104T164756
[2023-01-04 13:47:56,068] {local_task_job.py:156} INFO - Task exited with return code 0
[2023-01-04 13:47:56,081] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
