[2023-01-04 06:01:35,383] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: populate_crypto_values.get_crypto_values scheduled__2021-07-31T07:00:00+00:00 [queued]>
[2023-01-04 06:01:35,393] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: populate_crypto_values.get_crypto_values scheduled__2021-07-31T07:00:00+00:00 [queued]>
[2023-01-04 06:01:35,393] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2023-01-04 06:01:35,393] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2023-01-04 06:01:35,393] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2023-01-04 06:01:35,406] {taskinstance.py:1377} INFO - Executing <Task(PythonOperator): get_crypto_values> on 2021-07-31 07:00:00+00:00
[2023-01-04 06:01:35,411] {standard_task_runner.py:52} INFO - Started process 15708 to run task
[2023-01-04 06:01:35,417] {standard_task_runner.py:79} INFO - Running: ['airflow', 'tasks', 'run', 'populate_crypto_values', 'get_crypto_values', 'scheduled__2021-07-31T07:00:00+00:00', '--job-id', '269', '--raw', '--subdir', 'DAGS_FOLDER/populate_crypto_values.py', '--cfg-path', '/tmp/tmp8am5j20d', '--error-file', '/tmp/tmputbqjnal']
[2023-01-04 06:01:35,418] {standard_task_runner.py:80} INFO - Job 269: Subtask get_crypto_values
[2023-01-04 06:01:35,479] {task_command.py:370} INFO - Running <TaskInstance: populate_crypto_values.get_crypto_values scheduled__2021-07-31T07:00:00+00:00 [running]> on host xuxon-virtual-machine
[2023-01-04 06:01:35,555] {taskinstance.py:1569} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=populate_crypto_values
AIRFLOW_CTX_TASK_ID=get_crypto_values
AIRFLOW_CTX_EXECUTION_DATE=2021-07-31T07:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2021-07-31T07:00:00+00:00
[2023-01-04 06:01:35,652] {logging_mixin.py:115} INFO - Attempt 1 to get the crypto values has failed. The api status was 429
[2023-01-04 06:01:35,652] {logging_mixin.py:115} INFO - The api response was {"status":{"error_code":429,"error_message":"You've exceeded the Rate Limit. Please visit https://www.coingecko.com/en/api/pricing to subscribe to our API plans for higher rate limits."}}
[2023-01-04 06:01:50,838] {logging_mixin.py:115} INFO - Attempt 2 to get the crypto values has failed. The api status was 429
[2023-01-04 06:01:50,838] {logging_mixin.py:115} INFO - The api response was {"status":{"error_code":429,"error_message":"You've exceeded the Rate Limit. Please visit https://www.coingecko.com/en/api/pricing to subscribe to our API plans for higher rate limits."}}
[2023-01-04 06:02:07,523] {logging_mixin.py:115} INFO - Attempt 3 to get the crypto values has failed. The api status was 429
[2023-01-04 06:02:07,524] {logging_mixin.py:115} INFO - The api response was {"status":{"error_code":429,"error_message":"You've exceeded the Rate Limit. Please visit https://www.coingecko.com/en/api/pricing to subscribe to our API plans for higher rate limits."}}
[2023-01-04 06:02:22,630] {logging_mixin.py:115} INFO - Attempt 4 to get the crypto values has failed. The api status was 429
[2023-01-04 06:02:22,631] {logging_mixin.py:115} INFO - The api response was {"status":{"error_code":429,"error_message":"You've exceeded the Rate Limit. Please visit https://www.coingecko.com/en/api/pricing to subscribe to our API plans for higher rate limits."}}
[2023-01-04 06:02:37,759] {logging_mixin.py:115} INFO - Attempt 5 to get the crypto values has failed. The api status was 429
[2023-01-04 06:02:37,760] {logging_mixin.py:115} INFO - The api response was {"status":{"error_code":429,"error_message":"You've exceeded the Rate Limit. Please visit https://www.coingecko.com/en/api/pricing to subscribe to our API plans for higher rate limits."}}
[2023-01-04 06:02:52,879] {logging_mixin.py:115} INFO - Attempt 6 to get the crypto values has failed. The api status was 429
[2023-01-04 06:02:52,879] {logging_mixin.py:115} INFO - The api response was {"status":{"error_code":429,"error_message":"You've exceeded the Rate Limit. Please visit https://www.coingecko.com/en/api/pricing to subscribe to our API plans for higher rate limits."}}
[2023-01-04 06:03:07,986] {logging_mixin.py:115} INFO - Attempt 7 to get the crypto values has failed. The api status was 429
[2023-01-04 06:03:07,986] {logging_mixin.py:115} INFO - The api response was {"status":{"error_code":429,"error_message":"You've exceeded the Rate Limit. Please visit https://www.coingecko.com/en/api/pricing to subscribe to our API plans for higher rate limits."}}
[2023-01-04 06:03:23,115] {logging_mixin.py:115} INFO - Attempt 8 to get the crypto values has failed. The api status was 429
[2023-01-04 06:03:23,117] {logging_mixin.py:115} INFO - The api response was {"status":{"error_code":429,"error_message":"You've exceeded the Rate Limit. Please visit https://www.coingecko.com/en/api/pricing to subscribe to our API plans for higher rate limits."}}
[2023-01-04 06:03:39,177] {logging_mixin.py:115} INFO - New rows have been added.
[2023-01-04 06:03:39,178] {python.py:173} INFO - Done. Returned value was: None
[2023-01-04 06:03:39,206] {taskinstance.py:1395} INFO - Marking task as SUCCESS. dag_id=populate_crypto_values, task_id=get_crypto_values, execution_date=20210731T070000, start_date=20230104T090135, end_date=20230104T090339
[2023-01-04 06:03:39,252] {local_task_job.py:156} INFO - Task exited with return code 0
[2023-01-04 06:03:39,264] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
