[2023-01-04 04:08:18,403] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: populate_crypto_values.get_crypto_values scheduled__2021-02-15T07:00:00+00:00 [queued]>
[2023-01-04 04:08:18,412] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: populate_crypto_values.get_crypto_values scheduled__2021-02-15T07:00:00+00:00 [queued]>
[2023-01-04 04:08:18,412] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2023-01-04 04:08:18,412] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2023-01-04 04:08:18,413] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2023-01-04 04:08:18,509] {taskinstance.py:1377} INFO - Executing <Task(PythonOperator): get_crypto_values> on 2021-02-15 07:00:00+00:00
[2023-01-04 04:08:18,516] {standard_task_runner.py:52} INFO - Started process 61003 to run task
[2023-01-04 04:08:18,555] {standard_task_runner.py:79} INFO - Running: ['airflow', 'tasks', 'run', 'populate_crypto_values', 'get_crypto_values', 'scheduled__2021-02-15T07:00:00+00:00', '--job-id', '74', '--raw', '--subdir', 'DAGS_FOLDER/populate_crypto_values.py', '--cfg-path', '/tmp/tmpwf8cjxzz', '--error-file', '/tmp/tmpfpmglgr2']
[2023-01-04 04:08:18,557] {standard_task_runner.py:80} INFO - Job 74: Subtask get_crypto_values
[2023-01-04 04:08:19,355] {task_command.py:370} INFO - Running <TaskInstance: populate_crypto_values.get_crypto_values scheduled__2021-02-15T07:00:00+00:00 [running]> on host xuxon-virtual-machine
[2023-01-04 04:08:19,983] {taskinstance.py:1569} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=populate_crypto_values
AIRFLOW_CTX_TASK_ID=get_crypto_values
AIRFLOW_CTX_EXECUTION_DATE=2021-02-15T07:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2021-02-15T07:00:00+00:00
[2023-01-04 04:08:21,649] {logging_mixin.py:115} INFO - Encountered errors while inserting rows: [{'index': 0, 'errors': [{'reason': 'invalid', 'location': 'snapshot_date', 'debugInfo': '', 'message': "Invalid date: '16-02-2021'"}]}, {'index': 1, 'errors': [{'reason': 'invalid', 'location': 'snapshot_date', 'debugInfo': '', 'message': "Invalid date: '16-02-2021'"}]}]
[2023-01-04 04:08:21,649] {python.py:173} INFO - Done. Returned value was: None
[2023-01-04 04:08:21,657] {taskinstance.py:1395} INFO - Marking task as SUCCESS. dag_id=populate_crypto_values, task_id=get_crypto_values, execution_date=20210215T070000, start_date=20230104T070818, end_date=20230104T070821
[2023-01-04 04:08:21,731] {local_task_job.py:156} INFO - Task exited with return code 0
[2023-01-04 04:08:21,756] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2023-01-04 05:21:35,595] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: populate_crypto_values.get_crypto_values scheduled__2021-02-15T07:00:00+00:00 [queued]>
[2023-01-04 05:21:35,624] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: populate_crypto_values.get_crypto_values scheduled__2021-02-15T07:00:00+00:00 [queued]>
[2023-01-04 05:21:35,624] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2023-01-04 05:21:35,625] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2023-01-04 05:21:35,625] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2023-01-04 05:21:35,641] {taskinstance.py:1377} INFO - Executing <Task(PythonOperator): get_crypto_values> on 2021-02-15 07:00:00+00:00
[2023-01-04 05:21:35,645] {standard_task_runner.py:52} INFO - Started process 8268 to run task
[2023-01-04 05:21:35,651] {standard_task_runner.py:79} INFO - Running: ['airflow', 'tasks', 'run', 'populate_crypto_values', 'get_crypto_values', 'scheduled__2021-02-15T07:00:00+00:00', '--job-id', '103', '--raw', '--subdir', 'DAGS_FOLDER/populate_crypto_values.py', '--cfg-path', '/tmp/tmpmbd7ely1', '--error-file', '/tmp/tmpt4_undt9']
[2023-01-04 05:21:35,652] {standard_task_runner.py:80} INFO - Job 103: Subtask get_crypto_values
[2023-01-04 05:21:35,714] {task_command.py:370} INFO - Running <TaskInstance: populate_crypto_values.get_crypto_values scheduled__2021-02-15T07:00:00+00:00 [running]> on host xuxon-virtual-machine
[2023-01-04 05:21:35,784] {taskinstance.py:1569} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=populate_crypto_values
AIRFLOW_CTX_TASK_ID=get_crypto_values
AIRFLOW_CTX_EXECUTION_DATE=2021-02-15T07:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2021-02-15T07:00:00+00:00
[2023-01-04 05:21:35,883] {logging_mixin.py:115} INFO - Attempt 1 to get the crypto values has failed. The api status was 429
[2023-01-04 05:21:35,883] {logging_mixin.py:115} INFO - The api response was {"status":{"error_code":429,"error_message":"You've exceeded the Rate Limit. Please visit https://www.coingecko.com/en/api/pricing to subscribe to our API plans for higher rate limits."}}
[2023-01-04 05:21:51,015] {logging_mixin.py:115} INFO - Attempt 2 to get the crypto values has failed. The api status was 429
[2023-01-04 05:21:51,019] {logging_mixin.py:115} INFO - The api response was {"status":{"error_code":429,"error_message":"You've exceeded the Rate Limit. Please visit https://www.coingecko.com/en/api/pricing to subscribe to our API plans for higher rate limits."}}
[2023-01-04 05:22:06,134] {logging_mixin.py:115} INFO - Attempt 3 to get the crypto values has failed. The api status was 429
[2023-01-04 05:22:06,135] {logging_mixin.py:115} INFO - The api response was {"status":{"error_code":429,"error_message":"You've exceeded the Rate Limit. Please visit https://www.coingecko.com/en/api/pricing to subscribe to our API plans for higher rate limits."}}
[2023-01-04 05:22:21,251] {logging_mixin.py:115} INFO - Attempt 4 to get the crypto values has failed. The api status was 429
[2023-01-04 05:22:21,252] {logging_mixin.py:115} INFO - The api response was {"status":{"error_code":429,"error_message":"You've exceeded the Rate Limit. Please visit https://www.coingecko.com/en/api/pricing to subscribe to our API plans for higher rate limits."}}
[2023-01-04 05:22:36,369] {logging_mixin.py:115} INFO - Attempt 5 to get the crypto values has failed. The api status was 429
[2023-01-04 05:22:36,370] {logging_mixin.py:115} INFO - The api response was {"status":{"error_code":429,"error_message":"You've exceeded the Rate Limit. Please visit https://www.coingecko.com/en/api/pricing to subscribe to our API plans for higher rate limits."}}
[2023-01-04 05:22:51,496] {logging_mixin.py:115} INFO - Attempt 6 to get the crypto values has failed. The api status was 429
[2023-01-04 05:22:51,496] {logging_mixin.py:115} INFO - The api response was {"status":{"error_code":429,"error_message":"You've exceeded the Rate Limit. Please visit https://www.coingecko.com/en/api/pricing to subscribe to our API plans for higher rate limits."}}
[2023-01-04 05:23:06,623] {logging_mixin.py:115} INFO - Attempt 7 to get the crypto values has failed. The api status was 429
[2023-01-04 05:23:06,624] {logging_mixin.py:115} INFO - The api response was {"status":{"error_code":429,"error_message":"You've exceeded the Rate Limit. Please visit https://www.coingecko.com/en/api/pricing to subscribe to our API plans for higher rate limits."}}
[2023-01-04 05:23:21,751] {logging_mixin.py:115} INFO - Attempt 8 to get the crypto values has failed. The api status was 429
[2023-01-04 05:23:21,753] {logging_mixin.py:115} INFO - The api response was {"status":{"error_code":429,"error_message":"You've exceeded the Rate Limit. Please visit https://www.coingecko.com/en/api/pricing to subscribe to our API plans for higher rate limits."}}
[2023-01-04 05:23:38,357] {logging_mixin.py:115} INFO - New rows have been added.
[2023-01-04 05:23:38,357] {python.py:173} INFO - Done. Returned value was: None
[2023-01-04 05:23:38,368] {taskinstance.py:1395} INFO - Marking task as SUCCESS. dag_id=populate_crypto_values, task_id=get_crypto_values, execution_date=20210215T070000, start_date=20230104T082135, end_date=20230104T082338
[2023-01-04 05:23:38,647] {local_task_job.py:156} INFO - Task exited with return code 0
[2023-01-04 05:23:38,666] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
