[2023-01-04 05:34:36,173] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: populate_crypto_values.get_crypto_values scheduled__2021-04-09T07:00:00+00:00 [queued]>
[2023-01-04 05:34:36,180] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: populate_crypto_values.get_crypto_values scheduled__2021-04-09T07:00:00+00:00 [queued]>
[2023-01-04 05:34:36,180] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2023-01-04 05:34:36,180] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2023-01-04 05:34:36,180] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2023-01-04 05:34:36,197] {taskinstance.py:1377} INFO - Executing <Task(PythonOperator): get_crypto_values> on 2021-04-09 07:00:00+00:00
[2023-01-04 05:34:36,202] {standard_task_runner.py:52} INFO - Started process 10622 to run task
[2023-01-04 05:34:36,209] {standard_task_runner.py:79} INFO - Running: ['airflow', 'tasks', 'run', 'populate_crypto_values', 'get_crypto_values', 'scheduled__2021-04-09T07:00:00+00:00', '--job-id', '156', '--raw', '--subdir', 'DAGS_FOLDER/populate_crypto_values.py', '--cfg-path', '/tmp/tmpt42534vp', '--error-file', '/tmp/tmp40_yogcp']
[2023-01-04 05:34:36,210] {standard_task_runner.py:80} INFO - Job 156: Subtask get_crypto_values
[2023-01-04 05:34:36,308] {task_command.py:370} INFO - Running <TaskInstance: populate_crypto_values.get_crypto_values scheduled__2021-04-09T07:00:00+00:00 [running]> on host xuxon-virtual-machine
[2023-01-04 05:34:36,383] {taskinstance.py:1569} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=populate_crypto_values
AIRFLOW_CTX_TASK_ID=get_crypto_values
AIRFLOW_CTX_EXECUTION_DATE=2021-04-09T07:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2021-04-09T07:00:00+00:00
[2023-01-04 05:34:36,476] {logging_mixin.py:115} INFO - Attempt 1 to get the crypto values has failed. The api status was 429
[2023-01-04 05:34:36,477] {logging_mixin.py:115} INFO - The api response was {"status":{"error_code":429,"error_message":"You've exceeded the Rate Limit. Please visit https://www.coingecko.com/en/api/pricing to subscribe to our API plans for higher rate limits."}}
[2023-01-04 05:34:51,567] {logging_mixin.py:115} INFO - Attempt 2 to get the crypto values has failed. The api status was 429
[2023-01-04 05:34:51,567] {logging_mixin.py:115} INFO - The api response was {"status":{"error_code":429,"error_message":"You've exceeded the Rate Limit. Please visit https://www.coingecko.com/en/api/pricing to subscribe to our API plans for higher rate limits."}}
[2023-01-04 05:35:06,658] {logging_mixin.py:115} INFO - Attempt 3 to get the crypto values has failed. The api status was 429
[2023-01-04 05:35:06,659] {logging_mixin.py:115} INFO - The api response was {"status":{"error_code":429,"error_message":"You've exceeded the Rate Limit. Please visit https://www.coingecko.com/en/api/pricing to subscribe to our API plans for higher rate limits."}}
[2023-01-04 05:35:21,817] {logging_mixin.py:115} INFO - Attempt 4 to get the crypto values has failed. The api status was 429
[2023-01-04 05:35:21,817] {logging_mixin.py:115} INFO - The api response was {"status":{"error_code":429,"error_message":"You've exceeded the Rate Limit. Please visit https://www.coingecko.com/en/api/pricing to subscribe to our API plans for higher rate limits."}}
[2023-01-04 05:35:36,932] {logging_mixin.py:115} INFO - Attempt 5 to get the crypto values has failed. The api status was 429
[2023-01-04 05:35:36,933] {logging_mixin.py:115} INFO - The api response was {"status":{"error_code":429,"error_message":"You've exceeded the Rate Limit. Please visit https://www.coingecko.com/en/api/pricing to subscribe to our API plans for higher rate limits."}}
[2023-01-04 05:35:52,042] {logging_mixin.py:115} INFO - Attempt 6 to get the crypto values has failed. The api status was 429
[2023-01-04 05:35:52,042] {logging_mixin.py:115} INFO - The api response was {"status":{"error_code":429,"error_message":"You've exceeded the Rate Limit. Please visit https://www.coingecko.com/en/api/pricing to subscribe to our API plans for higher rate limits."}}
[2023-01-04 05:36:07,173] {logging_mixin.py:115} INFO - Attempt 7 to get the crypto values has failed. The api status was 429
[2023-01-04 05:36:07,174] {logging_mixin.py:115} INFO - The api response was {"status":{"error_code":429,"error_message":"You've exceeded the Rate Limit. Please visit https://www.coingecko.com/en/api/pricing to subscribe to our API plans for higher rate limits."}}
[2023-01-04 05:36:22,285] {logging_mixin.py:115} INFO - Attempt 8 to get the crypto values has failed. The api status was 429
[2023-01-04 05:36:22,285] {logging_mixin.py:115} INFO - The api response was {"status":{"error_code":429,"error_message":"You've exceeded the Rate Limit. Please visit https://www.coingecko.com/en/api/pricing to subscribe to our API plans for higher rate limits."}}
[2023-01-04 05:36:38,564] {logging_mixin.py:115} INFO - New rows have been added.
[2023-01-04 05:36:38,565] {python.py:173} INFO - Done. Returned value was: None
[2023-01-04 05:36:38,574] {taskinstance.py:1395} INFO - Marking task as SUCCESS. dag_id=populate_crypto_values, task_id=get_crypto_values, execution_date=20210409T070000, start_date=20230104T083436, end_date=20230104T083638
[2023-01-04 05:36:38,639] {local_task_job.py:156} INFO - Task exited with return code 0
[2023-01-04 05:36:38,652] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
