[2023-01-04 13:33:47,227] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: populate_crypto_values.get_crypto_values scheduled__2022-08-02T07:00:00+00:00 [queued]>
[2023-01-04 13:33:47,242] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: populate_crypto_values.get_crypto_values scheduled__2022-08-02T07:00:00+00:00 [queued]>
[2023-01-04 13:33:47,242] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2023-01-04 13:33:47,243] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2023-01-04 13:33:47,243] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2023-01-04 13:33:47,275] {taskinstance.py:1377} INFO - Executing <Task(PythonOperator): get_crypto_values> on 2022-08-02 07:00:00+00:00
[2023-01-04 13:33:47,280] {standard_task_runner.py:52} INFO - Started process 30506 to run task
[2023-01-04 13:33:47,286] {standard_task_runner.py:79} INFO - Running: ['airflow', 'tasks', 'run', 'populate_crypto_values', 'get_crypto_values', 'scheduled__2022-08-02T07:00:00+00:00', '--job-id', '639', '--raw', '--subdir', 'DAGS_FOLDER/populate_crypto_values.py', '--cfg-path', '/tmp/tmpryeyydul', '--error-file', '/tmp/tmpc8qykxzz']
[2023-01-04 13:33:47,287] {standard_task_runner.py:80} INFO - Job 639: Subtask get_crypto_values
[2023-01-04 13:33:47,342] {task_command.py:370} INFO - Running <TaskInstance: populate_crypto_values.get_crypto_values scheduled__2022-08-02T07:00:00+00:00 [running]> on host xuxon-virtual-machine
[2023-01-04 13:33:47,417] {taskinstance.py:1569} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=populate_crypto_values
AIRFLOW_CTX_TASK_ID=get_crypto_values
AIRFLOW_CTX_EXECUTION_DATE=2022-08-02T07:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-08-02T07:00:00+00:00
[2023-01-04 13:33:47,509] {logging_mixin.py:115} INFO - Attempt 1 to get the crypto values has failed. The api status was 429
[2023-01-04 13:33:47,509] {logging_mixin.py:115} INFO - The api response was {"status":{"error_code":429,"error_message":"You've exceeded the Rate Limit. Please visit https://www.coingecko.com/en/api/pricing to subscribe to our API plans for higher rate limits."}}
[2023-01-04 13:34:02,635] {logging_mixin.py:115} INFO - Attempt 2 to get the crypto values has failed. The api status was 429
[2023-01-04 13:34:02,635] {logging_mixin.py:115} INFO - The api response was {"status":{"error_code":429,"error_message":"You've exceeded the Rate Limit. Please visit https://www.coingecko.com/en/api/pricing to subscribe to our API plans for higher rate limits."}}
[2023-01-04 13:34:17,747] {logging_mixin.py:115} INFO - Attempt 3 to get the crypto values has failed. The api status was 429
[2023-01-04 13:34:17,749] {logging_mixin.py:115} INFO - The api response was {"status":{"error_code":429,"error_message":"You've exceeded the Rate Limit. Please visit https://www.coingecko.com/en/api/pricing to subscribe to our API plans for higher rate limits."}}
[2023-01-04 13:34:32,870] {logging_mixin.py:115} INFO - Attempt 4 to get the crypto values has failed. The api status was 429
[2023-01-04 13:34:32,871] {logging_mixin.py:115} INFO - The api response was {"status":{"error_code":429,"error_message":"You've exceeded the Rate Limit. Please visit https://www.coingecko.com/en/api/pricing to subscribe to our API plans for higher rate limits."}}
[2023-01-04 13:34:47,968] {logging_mixin.py:115} INFO - Attempt 5 to get the crypto values has failed. The api status was 429
[2023-01-04 13:34:47,968] {logging_mixin.py:115} INFO - The api response was {"status":{"error_code":429,"error_message":"You've exceeded the Rate Limit. Please visit https://www.coingecko.com/en/api/pricing to subscribe to our API plans for higher rate limits."}}
[2023-01-04 13:35:03,078] {logging_mixin.py:115} INFO - Attempt 6 to get the crypto values has failed. The api status was 429
[2023-01-04 13:35:03,080] {logging_mixin.py:115} INFO - The api response was {"status":{"error_code":429,"error_message":"You've exceeded the Rate Limit. Please visit https://www.coingecko.com/en/api/pricing to subscribe to our API plans for higher rate limits."}}
[2023-01-04 13:35:18,229] {logging_mixin.py:115} INFO - Attempt 7 to get the crypto values has failed. The api status was 429
[2023-01-04 13:35:18,229] {logging_mixin.py:115} INFO - The api response was {"status":{"error_code":429,"error_message":"You've exceeded the Rate Limit. Please visit https://www.coingecko.com/en/api/pricing to subscribe to our API plans for higher rate limits."}}
[2023-01-04 13:35:33,359] {logging_mixin.py:115} INFO - Attempt 8 to get the crypto values has failed. The api status was 429
[2023-01-04 13:35:33,360] {logging_mixin.py:115} INFO - The api response was {"status":{"error_code":429,"error_message":"You've exceeded the Rate Limit. Please visit https://www.coingecko.com/en/api/pricing to subscribe to our API plans for higher rate limits."}}
[2023-01-04 13:35:50,051] {logging_mixin.py:115} INFO - New rows have been added.
[2023-01-04 13:35:50,052] {python.py:173} INFO - Done. Returned value was: None
[2023-01-04 13:35:50,145] {taskinstance.py:1395} INFO - Marking task as SUCCESS. dag_id=populate_crypto_values, task_id=get_crypto_values, execution_date=20220802T070000, start_date=20230104T163347, end_date=20230104T163550
[2023-01-04 13:35:50,244] {local_task_job.py:156} INFO - Task exited with return code 0
[2023-01-04 13:35:50,276] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
