[2023-01-04 13:10:47,783] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: populate_crypto_values.get_crypto_values scheduled__2022-04-25T07:00:00+00:00 [queued]>
[2023-01-04 13:10:47,790] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: populate_crypto_values.get_crypto_values scheduled__2022-04-25T07:00:00+00:00 [queued]>
[2023-01-04 13:10:47,790] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2023-01-04 13:10:47,790] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2023-01-04 13:10:47,790] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2023-01-04 13:10:47,804] {taskinstance.py:1377} INFO - Executing <Task(PythonOperator): get_crypto_values> on 2022-04-25 07:00:00+00:00
[2023-01-04 13:10:47,808] {standard_task_runner.py:52} INFO - Started process 28020 to run task
[2023-01-04 13:10:47,813] {standard_task_runner.py:79} INFO - Running: ['airflow', 'tasks', 'run', 'populate_crypto_values', 'get_crypto_values', 'scheduled__2022-04-25T07:00:00+00:00', '--job-id', '540', '--raw', '--subdir', 'DAGS_FOLDER/populate_crypto_values.py', '--cfg-path', '/tmp/tmpmtjffzul', '--error-file', '/tmp/tmp9e2yavq_']
[2023-01-04 13:10:47,814] {standard_task_runner.py:80} INFO - Job 540: Subtask get_crypto_values
[2023-01-04 13:10:47,880] {task_command.py:370} INFO - Running <TaskInstance: populate_crypto_values.get_crypto_values scheduled__2022-04-25T07:00:00+00:00 [running]> on host xuxon-virtual-machine
[2023-01-04 13:10:47,942] {taskinstance.py:1569} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=populate_crypto_values
AIRFLOW_CTX_TASK_ID=get_crypto_values
AIRFLOW_CTX_EXECUTION_DATE=2022-04-25T07:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-04-25T07:00:00+00:00
[2023-01-04 13:10:48,036] {logging_mixin.py:115} INFO - Attempt 1 to get the crypto values has failed. The api status was 429
[2023-01-04 13:10:48,037] {logging_mixin.py:115} INFO - The api response was {"status":{"error_code":429,"error_message":"You've exceeded the Rate Limit. Please visit https://www.coingecko.com/en/api/pricing to subscribe to our API plans for higher rate limits."}}
[2023-01-04 13:11:03,177] {logging_mixin.py:115} INFO - Attempt 2 to get the crypto values has failed. The api status was 429
[2023-01-04 13:11:03,177] {logging_mixin.py:115} INFO - The api response was {"status":{"error_code":429,"error_message":"You've exceeded the Rate Limit. Please visit https://www.coingecko.com/en/api/pricing to subscribe to our API plans for higher rate limits."}}
[2023-01-04 13:11:18,316] {logging_mixin.py:115} INFO - Attempt 3 to get the crypto values has failed. The api status was 429
[2023-01-04 13:11:18,318] {logging_mixin.py:115} INFO - The api response was {"status":{"error_code":429,"error_message":"You've exceeded the Rate Limit. Please visit https://www.coingecko.com/en/api/pricing to subscribe to our API plans for higher rate limits."}}
[2023-01-04 13:11:33,463] {logging_mixin.py:115} INFO - Attempt 4 to get the crypto values has failed. The api status was 429
[2023-01-04 13:11:33,464] {logging_mixin.py:115} INFO - The api response was {"status":{"error_code":429,"error_message":"You've exceeded the Rate Limit. Please visit https://www.coingecko.com/en/api/pricing to subscribe to our API plans for higher rate limits."}}
[2023-01-04 13:11:48,716] {logging_mixin.py:115} INFO - Attempt 5 to get the crypto values has failed. The api status was 429
[2023-01-04 13:11:48,717] {logging_mixin.py:115} INFO - The api response was {"status":{"error_code":429,"error_message":"You've exceeded the Rate Limit. Please visit https://www.coingecko.com/en/api/pricing to subscribe to our API plans for higher rate limits."}}
[2023-01-04 13:12:03,844] {logging_mixin.py:115} INFO - Attempt 6 to get the crypto values has failed. The api status was 429
[2023-01-04 13:12:03,845] {logging_mixin.py:115} INFO - The api response was {"status":{"error_code":429,"error_message":"You've exceeded the Rate Limit. Please visit https://www.coingecko.com/en/api/pricing to subscribe to our API plans for higher rate limits."}}
[2023-01-04 13:12:18,959] {logging_mixin.py:115} INFO - Attempt 7 to get the crypto values has failed. The api status was 429
[2023-01-04 13:12:18,961] {logging_mixin.py:115} INFO - The api response was {"status":{"error_code":429,"error_message":"You've exceeded the Rate Limit. Please visit https://www.coingecko.com/en/api/pricing to subscribe to our API plans for higher rate limits."}}
[2023-01-04 13:12:34,095] {logging_mixin.py:115} INFO - Attempt 8 to get the crypto values has failed. The api status was 429
[2023-01-04 13:12:34,097] {logging_mixin.py:115} INFO - The api response was {"status":{"error_code":429,"error_message":"You've exceeded the Rate Limit. Please visit https://www.coingecko.com/en/api/pricing to subscribe to our API plans for higher rate limits."}}
[2023-01-04 13:12:50,169] {logging_mixin.py:115} INFO - New rows have been added.
[2023-01-04 13:12:50,170] {python.py:173} INFO - Done. Returned value was: None
[2023-01-04 13:12:50,191] {taskinstance.py:1395} INFO - Marking task as SUCCESS. dag_id=populate_crypto_values, task_id=get_crypto_values, execution_date=20220425T070000, start_date=20230104T161047, end_date=20230104T161250
[2023-01-04 13:12:50,266] {local_task_job.py:156} INFO - Task exited with return code 0
[2023-01-04 13:12:50,301] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
