[2023-01-04 12:47:31,232] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: populate_crypto_values.get_crypto_values scheduled__2022-01-31T07:00:00+00:00 [queued]>
[2023-01-04 12:47:31,238] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: populate_crypto_values.get_crypto_values scheduled__2022-01-31T07:00:00+00:00 [queued]>
[2023-01-04 12:47:31,238] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2023-01-04 12:47:31,238] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2023-01-04 12:47:31,239] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2023-01-04 12:47:31,270] {taskinstance.py:1377} INFO - Executing <Task(PythonOperator): get_crypto_values> on 2022-01-31 07:00:00+00:00
[2023-01-04 12:47:31,274] {standard_task_runner.py:52} INFO - Started process 25593 to run task
[2023-01-04 12:47:31,279] {standard_task_runner.py:79} INFO - Running: ['airflow', 'tasks', 'run', 'populate_crypto_values', 'get_crypto_values', 'scheduled__2022-01-31T07:00:00+00:00', '--job-id', '456', '--raw', '--subdir', 'DAGS_FOLDER/populate_crypto_values.py', '--cfg-path', '/tmp/tmpr5a4_ak8', '--error-file', '/tmp/tmpwb6i_g2w']
[2023-01-04 12:47:31,280] {standard_task_runner.py:80} INFO - Job 456: Subtask get_crypto_values
[2023-01-04 12:47:31,332] {task_command.py:370} INFO - Running <TaskInstance: populate_crypto_values.get_crypto_values scheduled__2022-01-31T07:00:00+00:00 [running]> on host xuxon-virtual-machine
[2023-01-04 12:47:31,413] {taskinstance.py:1569} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=populate_crypto_values
AIRFLOW_CTX_TASK_ID=get_crypto_values
AIRFLOW_CTX_EXECUTION_DATE=2022-01-31T07:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-01-31T07:00:00+00:00
[2023-01-04 12:47:31,511] {logging_mixin.py:115} INFO - Attempt 1 to get the crypto values has failed. The api status was 429
[2023-01-04 12:47:31,511] {logging_mixin.py:115} INFO - The api response was {"status":{"error_code":429,"error_message":"You've exceeded the Rate Limit. Please visit https://www.coingecko.com/en/api/pricing to subscribe to our API plans for higher rate limits."}}
[2023-01-04 12:47:46,640] {logging_mixin.py:115} INFO - Attempt 2 to get the crypto values has failed. The api status was 429
[2023-01-04 12:47:46,641] {logging_mixin.py:115} INFO - The api response was {"status":{"error_code":429,"error_message":"You've exceeded the Rate Limit. Please visit https://www.coingecko.com/en/api/pricing to subscribe to our API plans for higher rate limits."}}
[2023-01-04 12:48:01,752] {logging_mixin.py:115} INFO - Attempt 3 to get the crypto values has failed. The api status was 429
[2023-01-04 12:48:01,753] {logging_mixin.py:115} INFO - The api response was {"status":{"error_code":429,"error_message":"You've exceeded the Rate Limit. Please visit https://www.coingecko.com/en/api/pricing to subscribe to our API plans for higher rate limits."}}
[2023-01-04 12:48:16,873] {logging_mixin.py:115} INFO - Attempt 4 to get the crypto values has failed. The api status was 429
[2023-01-04 12:48:16,874] {logging_mixin.py:115} INFO - The api response was {"status":{"error_code":429,"error_message":"You've exceeded the Rate Limit. Please visit https://www.coingecko.com/en/api/pricing to subscribe to our API plans for higher rate limits."}}
[2023-01-04 12:48:32,008] {logging_mixin.py:115} INFO - Attempt 5 to get the crypto values has failed. The api status was 429
[2023-01-04 12:48:32,009] {logging_mixin.py:115} INFO - The api response was {"status":{"error_code":429,"error_message":"You've exceeded the Rate Limit. Please visit https://www.coingecko.com/en/api/pricing to subscribe to our API plans for higher rate limits."}}
[2023-01-04 12:48:47,135] {logging_mixin.py:115} INFO - Attempt 6 to get the crypto values has failed. The api status was 429
[2023-01-04 12:48:47,136] {logging_mixin.py:115} INFO - The api response was {"status":{"error_code":429,"error_message":"You've exceeded the Rate Limit. Please visit https://www.coingecko.com/en/api/pricing to subscribe to our API plans for higher rate limits."}}
[2023-01-04 12:49:02,236] {logging_mixin.py:115} INFO - Attempt 7 to get the crypto values has failed. The api status was 429
[2023-01-04 12:49:02,237] {logging_mixin.py:115} INFO - The api response was {"status":{"error_code":429,"error_message":"You've exceeded the Rate Limit. Please visit https://www.coingecko.com/en/api/pricing to subscribe to our API plans for higher rate limits."}}
[2023-01-04 12:49:17,449] {logging_mixin.py:115} INFO - Attempt 8 to get the crypto values has failed. The api status was 429
[2023-01-04 12:49:17,449] {logging_mixin.py:115} INFO - The api response was {"status":{"error_code":429,"error_message":"You've exceeded the Rate Limit. Please visit https://www.coingecko.com/en/api/pricing to subscribe to our API plans for higher rate limits."}}
[2023-01-04 12:49:33,614] {logging_mixin.py:115} INFO - New rows have been added.
[2023-01-04 12:49:33,614] {python.py:173} INFO - Done. Returned value was: None
[2023-01-04 12:49:33,637] {taskinstance.py:1395} INFO - Marking task as SUCCESS. dag_id=populate_crypto_values, task_id=get_crypto_values, execution_date=20220131T070000, start_date=20230104T154731, end_date=20230104T154933
[2023-01-04 12:49:33,708] {local_task_job.py:156} INFO - Task exited with return code 0
[2023-01-04 12:49:33,737] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
