[2023-01-04 06:18:53,070] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: populate_crypto_values.get_crypto_values scheduled__2021-10-08T07:00:00+00:00 [queued]>
[2023-01-04 06:18:53,088] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: populate_crypto_values.get_crypto_values scheduled__2021-10-08T07:00:00+00:00 [queued]>
[2023-01-04 06:18:53,088] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2023-01-04 06:18:53,088] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2023-01-04 06:18:53,088] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2023-01-04 06:18:53,195] {taskinstance.py:1377} INFO - Executing <Task(PythonOperator): get_crypto_values> on 2021-10-08 07:00:00+00:00
[2023-01-04 06:18:53,205] {standard_task_runner.py:52} INFO - Started process 18875 to run task
[2023-01-04 06:18:53,217] {standard_task_runner.py:79} INFO - Running: ['airflow', 'tasks', 'run', 'populate_crypto_values', 'get_crypto_values', 'scheduled__2021-10-08T07:00:00+00:00', '--job-id', '338', '--raw', '--subdir', 'DAGS_FOLDER/populate_crypto_values.py', '--cfg-path', '/tmp/tmp7wwe6spo', '--error-file', '/tmp/tmpopwcy6o1']
[2023-01-04 06:18:53,218] {standard_task_runner.py:80} INFO - Job 338: Subtask get_crypto_values
[2023-01-04 06:18:53,290] {task_command.py:370} INFO - Running <TaskInstance: populate_crypto_values.get_crypto_values scheduled__2021-10-08T07:00:00+00:00 [running]> on host xuxon-virtual-machine
[2023-01-04 06:18:53,403] {taskinstance.py:1569} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=populate_crypto_values
AIRFLOW_CTX_TASK_ID=get_crypto_values
AIRFLOW_CTX_EXECUTION_DATE=2021-10-08T07:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2021-10-08T07:00:00+00:00
[2023-01-04 06:18:53,512] {logging_mixin.py:115} INFO - Attempt 1 to get the crypto values has failed. The api status was 429
[2023-01-04 06:18:53,513] {logging_mixin.py:115} INFO - The api response was {"status":{"error_code":429,"error_message":"You've exceeded the Rate Limit. Please visit https://www.coingecko.com/en/api/pricing to subscribe to our API plans for higher rate limits."}}
[2023-01-04 06:19:08,621] {logging_mixin.py:115} INFO - Attempt 2 to get the crypto values has failed. The api status was 429
[2023-01-04 06:19:08,622] {logging_mixin.py:115} INFO - The api response was {"status":{"error_code":429,"error_message":"You've exceeded the Rate Limit. Please visit https://www.coingecko.com/en/api/pricing to subscribe to our API plans for higher rate limits."}}
[2023-01-04 06:19:23,737] {logging_mixin.py:115} INFO - Attempt 3 to get the crypto values has failed. The api status was 429
[2023-01-04 06:19:23,737] {logging_mixin.py:115} INFO - The api response was {"status":{"error_code":429,"error_message":"You've exceeded the Rate Limit. Please visit https://www.coingecko.com/en/api/pricing to subscribe to our API plans for higher rate limits."}}
[2023-01-04 06:19:38,835] {logging_mixin.py:115} INFO - Attempt 4 to get the crypto values has failed. The api status was 429
[2023-01-04 06:19:38,836] {logging_mixin.py:115} INFO - The api response was {"status":{"error_code":429,"error_message":"You've exceeded the Rate Limit. Please visit https://www.coingecko.com/en/api/pricing to subscribe to our API plans for higher rate limits."}}
[2023-01-04 06:19:53,978] {logging_mixin.py:115} INFO - Attempt 5 to get the crypto values has failed. The api status was 429
[2023-01-04 06:19:53,978] {logging_mixin.py:115} INFO - The api response was {"status":{"error_code":429,"error_message":"You've exceeded the Rate Limit. Please visit https://www.coingecko.com/en/api/pricing to subscribe to our API plans for higher rate limits."}}
[2023-01-04 06:20:09,146] {logging_mixin.py:115} INFO - Attempt 6 to get the crypto values has failed. The api status was 429
[2023-01-04 06:20:09,146] {logging_mixin.py:115} INFO - The api response was {"status":{"error_code":429,"error_message":"You've exceeded the Rate Limit. Please visit https://www.coingecko.com/en/api/pricing to subscribe to our API plans for higher rate limits."}}
[2023-01-04 06:20:24,257] {logging_mixin.py:115} INFO - Attempt 7 to get the crypto values has failed. The api status was 429
[2023-01-04 06:20:24,257] {logging_mixin.py:115} INFO - The api response was {"status":{"error_code":429,"error_message":"You've exceeded the Rate Limit. Please visit https://www.coingecko.com/en/api/pricing to subscribe to our API plans for higher rate limits."}}
[2023-01-04 06:20:39,420] {logging_mixin.py:115} INFO - Attempt 8 to get the crypto values has failed. The api status was 429
[2023-01-04 06:20:39,421] {logging_mixin.py:115} INFO - The api response was {"status":{"error_code":429,"error_message":"You've exceeded the Rate Limit. Please visit https://www.coingecko.com/en/api/pricing to subscribe to our API plans for higher rate limits."}}
[2023-01-04 06:20:55,604] {logging_mixin.py:115} INFO - New rows have been added.
[2023-01-04 06:20:55,604] {python.py:173} INFO - Done. Returned value was: None
[2023-01-04 06:20:55,618] {taskinstance.py:1395} INFO - Marking task as SUCCESS. dag_id=populate_crypto_values, task_id=get_crypto_values, execution_date=20211008T070000, start_date=20230104T091853, end_date=20230104T092055
[2023-01-04 06:20:55,649] {local_task_job.py:156} INFO - Task exited with return code 0
[2023-01-04 06:20:55,662] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
