[2023-01-04 05:43:28,921] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: populate_crypto_values.get_crypto_values scheduled__2021-05-18T07:00:00+00:00 [queued]>
[2023-01-04 05:43:28,927] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: populate_crypto_values.get_crypto_values scheduled__2021-05-18T07:00:00+00:00 [queued]>
[2023-01-04 05:43:28,927] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2023-01-04 05:43:28,927] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2023-01-04 05:43:28,927] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2023-01-04 05:43:28,943] {taskinstance.py:1377} INFO - Executing <Task(PythonOperator): get_crypto_values> on 2021-05-18 07:00:00+00:00
[2023-01-04 05:43:28,948] {standard_task_runner.py:52} INFO - Started process 12334 to run task
[2023-01-04 05:43:28,953] {standard_task_runner.py:79} INFO - Running: ['airflow', 'tasks', 'run', 'populate_crypto_values', 'get_crypto_values', 'scheduled__2021-05-18T07:00:00+00:00', '--job-id', '195', '--raw', '--subdir', 'DAGS_FOLDER/populate_crypto_values.py', '--cfg-path', '/tmp/tmp_n2d36vd', '--error-file', '/tmp/tmpo46xcmb1']
[2023-01-04 05:43:28,954] {standard_task_runner.py:80} INFO - Job 195: Subtask get_crypto_values
[2023-01-04 05:43:29,008] {task_command.py:370} INFO - Running <TaskInstance: populate_crypto_values.get_crypto_values scheduled__2021-05-18T07:00:00+00:00 [running]> on host xuxon-virtual-machine
[2023-01-04 05:43:29,085] {taskinstance.py:1569} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=populate_crypto_values
AIRFLOW_CTX_TASK_ID=get_crypto_values
AIRFLOW_CTX_EXECUTION_DATE=2021-05-18T07:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2021-05-18T07:00:00+00:00
[2023-01-04 05:43:29,935] {logging_mixin.py:115} INFO - Attempt 1 to get the crypto values has failed. The api status was 429
[2023-01-04 05:43:29,936] {logging_mixin.py:115} INFO - The api response was {"status":{"error_code":429,"error_message":"You've exceeded the Rate Limit. Please visit https://www.coingecko.com/en/api/pricing to subscribe to our API plans for higher rate limits."}}
[2023-01-04 05:43:45,056] {logging_mixin.py:115} INFO - Attempt 2 to get the crypto values has failed. The api status was 429
[2023-01-04 05:43:45,057] {logging_mixin.py:115} INFO - The api response was {"status":{"error_code":429,"error_message":"You've exceeded the Rate Limit. Please visit https://www.coingecko.com/en/api/pricing to subscribe to our API plans for higher rate limits."}}
[2023-01-04 05:44:00,181] {logging_mixin.py:115} INFO - Attempt 3 to get the crypto values has failed. The api status was 429
[2023-01-04 05:44:00,182] {logging_mixin.py:115} INFO - The api response was {"status":{"error_code":429,"error_message":"You've exceeded the Rate Limit. Please visit https://www.coingecko.com/en/api/pricing to subscribe to our API plans for higher rate limits."}}
[2023-01-04 05:44:15,311] {logging_mixin.py:115} INFO - Attempt 4 to get the crypto values has failed. The api status was 429
[2023-01-04 05:44:15,313] {logging_mixin.py:115} INFO - The api response was {"status":{"error_code":429,"error_message":"You've exceeded the Rate Limit. Please visit https://www.coingecko.com/en/api/pricing to subscribe to our API plans for higher rate limits."}}
[2023-01-04 05:44:30,433] {logging_mixin.py:115} INFO - Attempt 5 to get the crypto values has failed. The api status was 429
[2023-01-04 05:44:30,433] {logging_mixin.py:115} INFO - The api response was {"status":{"error_code":429,"error_message":"You've exceeded the Rate Limit. Please visit https://www.coingecko.com/en/api/pricing to subscribe to our API plans for higher rate limits."}}
[2023-01-04 05:44:45,549] {logging_mixin.py:115} INFO - Attempt 6 to get the crypto values has failed. The api status was 429
[2023-01-04 05:44:45,550] {logging_mixin.py:115} INFO - The api response was {"status":{"error_code":429,"error_message":"You've exceeded the Rate Limit. Please visit https://www.coingecko.com/en/api/pricing to subscribe to our API plans for higher rate limits."}}
[2023-01-04 05:45:00,669] {logging_mixin.py:115} INFO - Attempt 7 to get the crypto values has failed. The api status was 429
[2023-01-04 05:45:00,670] {logging_mixin.py:115} INFO - The api response was {"status":{"error_code":429,"error_message":"You've exceeded the Rate Limit. Please visit https://www.coingecko.com/en/api/pricing to subscribe to our API plans for higher rate limits."}}
[2023-01-04 05:45:15,786] {logging_mixin.py:115} INFO - Attempt 8 to get the crypto values has failed. The api status was 429
[2023-01-04 05:45:15,788] {logging_mixin.py:115} INFO - The api response was {"status":{"error_code":429,"error_message":"You've exceeded the Rate Limit. Please visit https://www.coingecko.com/en/api/pricing to subscribe to our API plans for higher rate limits."}}
[2023-01-04 05:45:31,562] {logging_mixin.py:115} INFO - New rows have been added.
[2023-01-04 05:45:31,563] {python.py:173} INFO - Done. Returned value was: None
[2023-01-04 05:45:31,571] {taskinstance.py:1395} INFO - Marking task as SUCCESS. dag_id=populate_crypto_values, task_id=get_crypto_values, execution_date=20210518T070000, start_date=20230104T084328, end_date=20230104T084531
[2023-01-04 05:45:31,619] {local_task_job.py:156} INFO - Task exited with return code 0
[2023-01-04 05:45:31,630] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
