[2023-01-04 13:23:40,045] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: populate_crypto_values.get_crypto_values scheduled__2022-06-18T07:00:00+00:00 [queued]>
[2023-01-04 13:23:40,052] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: populate_crypto_values.get_crypto_values scheduled__2022-06-18T07:00:00+00:00 [queued]>
[2023-01-04 13:23:40,052] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2023-01-04 13:23:40,052] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2023-01-04 13:23:40,052] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2023-01-04 13:23:40,065] {taskinstance.py:1377} INFO - Executing <Task(PythonOperator): get_crypto_values> on 2022-06-18 07:00:00+00:00
[2023-01-04 13:23:40,069] {standard_task_runner.py:52} INFO - Started process 29439 to run task
[2023-01-04 13:23:40,075] {standard_task_runner.py:79} INFO - Running: ['airflow', 'tasks', 'run', 'populate_crypto_values', 'get_crypto_values', 'scheduled__2022-06-18T07:00:00+00:00', '--job-id', '594', '--raw', '--subdir', 'DAGS_FOLDER/populate_crypto_values.py', '--cfg-path', '/tmp/tmpombg_29m', '--error-file', '/tmp/tmpbr8fsxwb']
[2023-01-04 13:23:40,076] {standard_task_runner.py:80} INFO - Job 594: Subtask get_crypto_values
[2023-01-04 13:23:40,149] {task_command.py:370} INFO - Running <TaskInstance: populate_crypto_values.get_crypto_values scheduled__2022-06-18T07:00:00+00:00 [running]> on host xuxon-virtual-machine
[2023-01-04 13:23:40,212] {taskinstance.py:1569} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=populate_crypto_values
AIRFLOW_CTX_TASK_ID=get_crypto_values
AIRFLOW_CTX_EXECUTION_DATE=2022-06-18T07:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-06-18T07:00:00+00:00
[2023-01-04 13:23:41,057] {logging_mixin.py:115} INFO - Attempt 1 to get the crypto values has failed. The api status was 429
[2023-01-04 13:23:41,059] {logging_mixin.py:115} INFO - The api response was {"status":{"error_code":429,"error_message":"You've exceeded the Rate Limit. Please visit https://www.coingecko.com/en/api/pricing to subscribe to our API plans for higher rate limits."}}
[2023-01-04 13:23:56,183] {logging_mixin.py:115} INFO - Attempt 2 to get the crypto values has failed. The api status was 429
[2023-01-04 13:23:56,185] {logging_mixin.py:115} INFO - The api response was {"status":{"error_code":429,"error_message":"You've exceeded the Rate Limit. Please visit https://www.coingecko.com/en/api/pricing to subscribe to our API plans for higher rate limits."}}
[2023-01-04 13:24:11,308] {logging_mixin.py:115} INFO - Attempt 3 to get the crypto values has failed. The api status was 429
[2023-01-04 13:24:11,308] {logging_mixin.py:115} INFO - The api response was {"status":{"error_code":429,"error_message":"You've exceeded the Rate Limit. Please visit https://www.coingecko.com/en/api/pricing to subscribe to our API plans for higher rate limits."}}
[2023-01-04 13:24:26,454] {logging_mixin.py:115} INFO - Attempt 4 to get the crypto values has failed. The api status was 429
[2023-01-04 13:24:26,455] {logging_mixin.py:115} INFO - The api response was {"status":{"error_code":429,"error_message":"You've exceeded the Rate Limit. Please visit https://www.coingecko.com/en/api/pricing to subscribe to our API plans for higher rate limits."}}
[2023-01-04 13:24:41,601] {logging_mixin.py:115} INFO - Attempt 5 to get the crypto values has failed. The api status was 429
[2023-01-04 13:24:41,602] {logging_mixin.py:115} INFO - The api response was {"status":{"error_code":429,"error_message":"You've exceeded the Rate Limit. Please visit https://www.coingecko.com/en/api/pricing to subscribe to our API plans for higher rate limits."}}
[2023-01-04 13:24:56,718] {logging_mixin.py:115} INFO - Attempt 6 to get the crypto values has failed. The api status was 429
[2023-01-04 13:24:56,719] {logging_mixin.py:115} INFO - The api response was {"status":{"error_code":429,"error_message":"You've exceeded the Rate Limit. Please visit https://www.coingecko.com/en/api/pricing to subscribe to our API plans for higher rate limits."}}
[2023-01-04 13:25:11,837] {logging_mixin.py:115} INFO - Attempt 7 to get the crypto values has failed. The api status was 429
[2023-01-04 13:25:11,838] {logging_mixin.py:115} INFO - The api response was {"status":{"error_code":429,"error_message":"You've exceeded the Rate Limit. Please visit https://www.coingecko.com/en/api/pricing to subscribe to our API plans for higher rate limits."}}
[2023-01-04 13:25:26,956] {logging_mixin.py:115} INFO - Attempt 8 to get the crypto values has failed. The api status was 429
[2023-01-04 13:25:26,957] {logging_mixin.py:115} INFO - The api response was {"status":{"error_code":429,"error_message":"You've exceeded the Rate Limit. Please visit https://www.coingecko.com/en/api/pricing to subscribe to our API plans for higher rate limits."}}
[2023-01-04 13:25:42,885] {logging_mixin.py:115} INFO - New rows have been added.
[2023-01-04 13:25:42,886] {python.py:173} INFO - Done. Returned value was: None
[2023-01-04 13:25:42,900] {taskinstance.py:1395} INFO - Marking task as SUCCESS. dag_id=populate_crypto_values, task_id=get_crypto_values, execution_date=20220618T070000, start_date=20230104T162340, end_date=20230104T162542
[2023-01-04 13:25:42,973] {local_task_job.py:156} INFO - Task exited with return code 0
[2023-01-04 13:25:42,983] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
