[2023-01-04 14:09:26,707] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: populate_crypto_values.get_crypto_values scheduled__2023-01-03T07:00:00+00:00 [queued]>
[2023-01-04 14:09:26,713] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: populate_crypto_values.get_crypto_values scheduled__2023-01-03T07:00:00+00:00 [queued]>
[2023-01-04 14:09:26,713] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2023-01-04 14:09:26,713] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2023-01-04 14:09:26,713] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2023-01-04 14:09:26,725] {taskinstance.py:1377} INFO - Executing <Task(PythonOperator): get_crypto_values> on 2023-01-03 07:00:00+00:00
[2023-01-04 14:09:26,729] {standard_task_runner.py:52} INFO - Started process 34339 to run task
[2023-01-04 14:09:26,735] {standard_task_runner.py:79} INFO - Running: ['airflow', 'tasks', 'run', 'populate_crypto_values', 'get_crypto_values', 'scheduled__2023-01-03T07:00:00+00:00', '--job-id', '793', '--raw', '--subdir', 'DAGS_FOLDER/populate_crypto_values.py', '--cfg-path', '/tmp/tmpxtmorm8n', '--error-file', '/tmp/tmpm0t0yooc']
[2023-01-04 14:09:26,736] {standard_task_runner.py:80} INFO - Job 793: Subtask get_crypto_values
[2023-01-04 14:09:26,784] {task_command.py:370} INFO - Running <TaskInstance: populate_crypto_values.get_crypto_values scheduled__2023-01-03T07:00:00+00:00 [running]> on host xuxon-virtual-machine
[2023-01-04 14:09:26,846] {taskinstance.py:1569} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=populate_crypto_values
AIRFLOW_CTX_TASK_ID=get_crypto_values
AIRFLOW_CTX_EXECUTION_DATE=2023-01-03T07:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2023-01-03T07:00:00+00:00
[2023-01-04 14:09:26,961] {logging_mixin.py:115} INFO - Attempt 1 to get the crypto values has failed. The api status was 429
[2023-01-04 14:09:26,961] {logging_mixin.py:115} INFO - The api response was {"status":{"error_code":429,"error_message":"You've exceeded the Rate Limit. Please visit https://www.coingecko.com/en/api/pricing to subscribe to our API plans for higher rate limits."}}
[2023-01-04 14:09:42,073] {logging_mixin.py:115} INFO - Attempt 2 to get the crypto values has failed. The api status was 429
[2023-01-04 14:09:42,074] {logging_mixin.py:115} INFO - The api response was {"status":{"error_code":429,"error_message":"You've exceeded the Rate Limit. Please visit https://www.coingecko.com/en/api/pricing to subscribe to our API plans for higher rate limits."}}
[2023-01-04 14:09:57,203] {logging_mixin.py:115} INFO - Attempt 3 to get the crypto values has failed. The api status was 429
[2023-01-04 14:09:57,204] {logging_mixin.py:115} INFO - The api response was {"status":{"error_code":429,"error_message":"You've exceeded the Rate Limit. Please visit https://www.coingecko.com/en/api/pricing to subscribe to our API plans for higher rate limits."}}
[2023-01-04 14:10:12,351] {logging_mixin.py:115} INFO - Attempt 4 to get the crypto values has failed. The api status was 429
[2023-01-04 14:10:12,351] {logging_mixin.py:115} INFO - The api response was {"status":{"error_code":429,"error_message":"You've exceeded the Rate Limit. Please visit https://www.coingecko.com/en/api/pricing to subscribe to our API plans for higher rate limits."}}
[2023-01-04 14:10:27,464] {logging_mixin.py:115} INFO - Attempt 5 to get the crypto values has failed. The api status was 429
[2023-01-04 14:10:27,464] {logging_mixin.py:115} INFO - The api response was {"status":{"error_code":429,"error_message":"You've exceeded the Rate Limit. Please visit https://www.coingecko.com/en/api/pricing to subscribe to our API plans for higher rate limits."}}
[2023-01-04 14:10:42,599] {logging_mixin.py:115} INFO - Attempt 6 to get the crypto values has failed. The api status was 429
[2023-01-04 14:10:42,600] {logging_mixin.py:115} INFO - The api response was {"status":{"error_code":429,"error_message":"You've exceeded the Rate Limit. Please visit https://www.coingecko.com/en/api/pricing to subscribe to our API plans for higher rate limits."}}
[2023-01-04 14:10:57,708] {logging_mixin.py:115} INFO - Attempt 7 to get the crypto values has failed. The api status was 429
[2023-01-04 14:10:57,709] {logging_mixin.py:115} INFO - The api response was {"status":{"error_code":429,"error_message":"You've exceeded the Rate Limit. Please visit https://www.coingecko.com/en/api/pricing to subscribe to our API plans for higher rate limits."}}
[2023-01-04 14:11:12,846] {logging_mixin.py:115} INFO - Attempt 8 to get the crypto values has failed. The api status was 429
[2023-01-04 14:11:12,847] {logging_mixin.py:115} INFO - The api response was {"status":{"error_code":429,"error_message":"You've exceeded the Rate Limit. Please visit https://www.coingecko.com/en/api/pricing to subscribe to our API plans for higher rate limits."}}
[2023-01-04 14:11:29,057] {logging_mixin.py:115} INFO - New rows have been added.
[2023-01-04 14:11:29,058] {python.py:173} INFO - Done. Returned value was: None
[2023-01-04 14:11:29,072] {taskinstance.py:1395} INFO - Marking task as SUCCESS. dag_id=populate_crypto_values, task_id=get_crypto_values, execution_date=20230103T070000, start_date=20230104T170926, end_date=20230104T171129
[2023-01-04 14:11:29,120] {local_task_job.py:156} INFO - Task exited with return code 0
[2023-01-04 14:11:29,134] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
