[2023-01-04 14:00:30,991] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: populate_crypto_values.get_crypto_values scheduled__2022-11-24T07:00:00+00:00 [queued]>
[2023-01-04 14:00:30,997] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: populate_crypto_values.get_crypto_values scheduled__2022-11-24T07:00:00+00:00 [queued]>
[2023-01-04 14:00:30,997] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2023-01-04 14:00:30,997] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2023-01-04 14:00:30,997] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2023-01-04 14:00:31,009] {taskinstance.py:1377} INFO - Executing <Task(PythonOperator): get_crypto_values> on 2022-11-24 07:00:00+00:00
[2023-01-04 14:00:31,013] {standard_task_runner.py:52} INFO - Started process 33372 to run task
[2023-01-04 14:00:31,019] {standard_task_runner.py:79} INFO - Running: ['airflow', 'tasks', 'run', 'populate_crypto_values', 'get_crypto_values', 'scheduled__2022-11-24T07:00:00+00:00', '--job-id', '753', '--raw', '--subdir', 'DAGS_FOLDER/populate_crypto_values.py', '--cfg-path', '/tmp/tmp7lhq42o8', '--error-file', '/tmp/tmpzgz2e_k4']
[2023-01-04 14:00:31,019] {standard_task_runner.py:80} INFO - Job 753: Subtask get_crypto_values
[2023-01-04 14:00:31,069] {task_command.py:370} INFO - Running <TaskInstance: populate_crypto_values.get_crypto_values scheduled__2022-11-24T07:00:00+00:00 [running]> on host xuxon-virtual-machine
[2023-01-04 14:00:31,143] {taskinstance.py:1569} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=populate_crypto_values
AIRFLOW_CTX_TASK_ID=get_crypto_values
AIRFLOW_CTX_EXECUTION_DATE=2022-11-24T07:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-11-24T07:00:00+00:00
[2023-01-04 14:00:31,240] {logging_mixin.py:115} INFO - Attempt 1 to get the crypto values has failed. The api status was 429
[2023-01-04 14:00:31,240] {logging_mixin.py:115} INFO - The api response was {"status":{"error_code":429,"error_message":"You've exceeded the Rate Limit. Please visit https://www.coingecko.com/en/api/pricing to subscribe to our API plans for higher rate limits."}}
[2023-01-04 14:00:46,363] {logging_mixin.py:115} INFO - Attempt 2 to get the crypto values has failed. The api status was 429
[2023-01-04 14:00:46,363] {logging_mixin.py:115} INFO - The api response was {"status":{"error_code":429,"error_message":"You've exceeded the Rate Limit. Please visit https://www.coingecko.com/en/api/pricing to subscribe to our API plans for higher rate limits."}}
[2023-01-04 14:01:01,505] {logging_mixin.py:115} INFO - Attempt 3 to get the crypto values has failed. The api status was 429
[2023-01-04 14:01:01,506] {logging_mixin.py:115} INFO - The api response was {"status":{"error_code":429,"error_message":"You've exceeded the Rate Limit. Please visit https://www.coingecko.com/en/api/pricing to subscribe to our API plans for higher rate limits."}}
[2023-01-04 14:01:16,620] {logging_mixin.py:115} INFO - Attempt 4 to get the crypto values has failed. The api status was 429
[2023-01-04 14:01:16,621] {logging_mixin.py:115} INFO - The api response was {"status":{"error_code":429,"error_message":"You've exceeded the Rate Limit. Please visit https://www.coingecko.com/en/api/pricing to subscribe to our API plans for higher rate limits."}}
[2023-01-04 14:01:31,738] {logging_mixin.py:115} INFO - Attempt 5 to get the crypto values has failed. The api status was 429
[2023-01-04 14:01:31,739] {logging_mixin.py:115} INFO - The api response was {"status":{"error_code":429,"error_message":"You've exceeded the Rate Limit. Please visit https://www.coingecko.com/en/api/pricing to subscribe to our API plans for higher rate limits."}}
[2023-01-04 14:01:46,843] {logging_mixin.py:115} INFO - Attempt 6 to get the crypto values has failed. The api status was 429
[2023-01-04 14:01:46,843] {logging_mixin.py:115} INFO - The api response was {"status":{"error_code":429,"error_message":"You've exceeded the Rate Limit. Please visit https://www.coingecko.com/en/api/pricing to subscribe to our API plans for higher rate limits."}}
[2023-01-04 14:02:01,991] {logging_mixin.py:115} INFO - Attempt 7 to get the crypto values has failed. The api status was 429
[2023-01-04 14:02:02,000] {logging_mixin.py:115} INFO - The api response was {"status":{"error_code":429,"error_message":"You've exceeded the Rate Limit. Please visit https://www.coingecko.com/en/api/pricing to subscribe to our API plans for higher rate limits."}}
[2023-01-04 14:02:17,123] {logging_mixin.py:115} INFO - Attempt 8 to get the crypto values has failed. The api status was 429
[2023-01-04 14:02:17,124] {logging_mixin.py:115} INFO - The api response was {"status":{"error_code":429,"error_message":"You've exceeded the Rate Limit. Please visit https://www.coingecko.com/en/api/pricing to subscribe to our API plans for higher rate limits."}}
[2023-01-04 14:02:33,162] {logging_mixin.py:115} INFO - New rows have been added.
[2023-01-04 14:02:33,162] {python.py:173} INFO - Done. Returned value was: None
[2023-01-04 14:02:33,172] {taskinstance.py:1395} INFO - Marking task as SUCCESS. dag_id=populate_crypto_values, task_id=get_crypto_values, execution_date=20221124T070000, start_date=20230104T170030, end_date=20230104T170233
[2023-01-04 14:02:33,224] {local_task_job.py:156} INFO - Task exited with return code 0
[2023-01-04 14:02:33,240] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
