[2023-01-04 05:27:45,972] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: populate_crypto_values.get_crypto_values scheduled__2021-03-12T07:00:00+00:00 [queued]>
[2023-01-04 05:27:45,978] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: populate_crypto_values.get_crypto_values scheduled__2021-03-12T07:00:00+00:00 [queued]>
[2023-01-04 05:27:45,979] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2023-01-04 05:27:45,979] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2023-01-04 05:27:45,979] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2023-01-04 05:27:45,994] {taskinstance.py:1377} INFO - Executing <Task(PythonOperator): get_crypto_values> on 2021-03-12 07:00:00+00:00
[2023-01-04 05:27:45,998] {standard_task_runner.py:52} INFO - Started process 9360 to run task
[2023-01-04 05:27:46,004] {standard_task_runner.py:79} INFO - Running: ['airflow', 'tasks', 'run', 'populate_crypto_values', 'get_crypto_values', 'scheduled__2021-03-12T07:00:00+00:00', '--job-id', '128', '--raw', '--subdir', 'DAGS_FOLDER/populate_crypto_values.py', '--cfg-path', '/tmp/tmpuiwodk2l', '--error-file', '/tmp/tmpu3840j0_']
[2023-01-04 05:27:46,005] {standard_task_runner.py:80} INFO - Job 128: Subtask get_crypto_values
[2023-01-04 05:27:46,057] {task_command.py:370} INFO - Running <TaskInstance: populate_crypto_values.get_crypto_values scheduled__2021-03-12T07:00:00+00:00 [running]> on host xuxon-virtual-machine
[2023-01-04 05:27:46,148] {taskinstance.py:1569} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=populate_crypto_values
AIRFLOW_CTX_TASK_ID=get_crypto_values
AIRFLOW_CTX_EXECUTION_DATE=2021-03-12T07:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2021-03-12T07:00:00+00:00
[2023-01-04 05:27:46,245] {logging_mixin.py:115} INFO - Attempt 1 to get the crypto values has failed. The api status was 429
[2023-01-04 05:27:46,245] {logging_mixin.py:115} INFO - The api response was {"status":{"error_code":429,"error_message":"You've exceeded the Rate Limit. Please visit https://www.coingecko.com/en/api/pricing to subscribe to our API plans for higher rate limits."}}
[2023-01-04 05:28:01,373] {logging_mixin.py:115} INFO - Attempt 2 to get the crypto values has failed. The api status was 429
[2023-01-04 05:28:01,374] {logging_mixin.py:115} INFO - The api response was {"status":{"error_code":429,"error_message":"You've exceeded the Rate Limit. Please visit https://www.coingecko.com/en/api/pricing to subscribe to our API plans for higher rate limits."}}
[2023-01-04 05:28:16,480] {logging_mixin.py:115} INFO - Attempt 3 to get the crypto values has failed. The api status was 429
[2023-01-04 05:28:16,481] {logging_mixin.py:115} INFO - The api response was {"status":{"error_code":429,"error_message":"You've exceeded the Rate Limit. Please visit https://www.coingecko.com/en/api/pricing to subscribe to our API plans for higher rate limits."}}
[2023-01-04 05:28:31,592] {logging_mixin.py:115} INFO - Attempt 4 to get the crypto values has failed. The api status was 429
[2023-01-04 05:28:31,594] {logging_mixin.py:115} INFO - The api response was {"status":{"error_code":429,"error_message":"You've exceeded the Rate Limit. Please visit https://www.coingecko.com/en/api/pricing to subscribe to our API plans for higher rate limits."}}
[2023-01-04 05:28:46,693] {logging_mixin.py:115} INFO - Attempt 5 to get the crypto values has failed. The api status was 429
[2023-01-04 05:28:46,694] {logging_mixin.py:115} INFO - The api response was {"status":{"error_code":429,"error_message":"You've exceeded the Rate Limit. Please visit https://www.coingecko.com/en/api/pricing to subscribe to our API plans for higher rate limits."}}
[2023-01-04 05:29:01,819] {logging_mixin.py:115} INFO - Attempt 6 to get the crypto values has failed. The api status was 429
[2023-01-04 05:29:01,820] {logging_mixin.py:115} INFO - The api response was {"status":{"error_code":429,"error_message":"You've exceeded the Rate Limit. Please visit https://www.coingecko.com/en/api/pricing to subscribe to our API plans for higher rate limits."}}
[2023-01-04 05:29:16,924] {logging_mixin.py:115} INFO - Attempt 7 to get the crypto values has failed. The api status was 429
[2023-01-04 05:29:16,925] {logging_mixin.py:115} INFO - The api response was {"status":{"error_code":429,"error_message":"You've exceeded the Rate Limit. Please visit https://www.coingecko.com/en/api/pricing to subscribe to our API plans for higher rate limits."}}
[2023-01-04 05:29:32,034] {logging_mixin.py:115} INFO - Attempt 8 to get the crypto values has failed. The api status was 429
[2023-01-04 05:29:32,035] {logging_mixin.py:115} INFO - The api response was {"status":{"error_code":429,"error_message":"You've exceeded the Rate Limit. Please visit https://www.coingecko.com/en/api/pricing to subscribe to our API plans for higher rate limits."}}
[2023-01-04 05:29:48,607] {logging_mixin.py:115} INFO - New rows have been added.
[2023-01-04 05:29:48,607] {python.py:173} INFO - Done. Returned value was: None
[2023-01-04 05:29:48,616] {taskinstance.py:1395} INFO - Marking task as SUCCESS. dag_id=populate_crypto_values, task_id=get_crypto_values, execution_date=20210312T070000, start_date=20230104T082745, end_date=20230104T082948
[2023-01-04 05:29:48,681] {local_task_job.py:156} INFO - Task exited with return code 0
[2023-01-04 05:29:48,696] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
