[2023-01-04 12:33:43,941] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: populate_crypto_values.get_crypto_values scheduled__2021-12-14T07:00:00+00:00 [queued]>
[2023-01-04 12:33:43,946] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: populate_crypto_values.get_crypto_values scheduled__2021-12-14T07:00:00+00:00 [queued]>
[2023-01-04 12:33:43,946] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2023-01-04 12:33:43,946] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2023-01-04 12:33:43,946] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2023-01-04 12:33:43,959] {taskinstance.py:1377} INFO - Executing <Task(PythonOperator): get_crypto_values> on 2021-12-14 07:00:00+00:00
[2023-01-04 12:33:43,963] {standard_task_runner.py:52} INFO - Started process 24304 to run task
[2023-01-04 12:33:43,968] {standard_task_runner.py:79} INFO - Running: ['airflow', 'tasks', 'run', 'populate_crypto_values', 'get_crypto_values', 'scheduled__2021-12-14T07:00:00+00:00', '--job-id', '408', '--raw', '--subdir', 'DAGS_FOLDER/populate_crypto_values.py', '--cfg-path', '/tmp/tmp7bemqcqb', '--error-file', '/tmp/tmpvmlr14aw']
[2023-01-04 12:33:43,969] {standard_task_runner.py:80} INFO - Job 408: Subtask get_crypto_values
[2023-01-04 12:33:44,016] {task_command.py:370} INFO - Running <TaskInstance: populate_crypto_values.get_crypto_values scheduled__2021-12-14T07:00:00+00:00 [running]> on host xuxon-virtual-machine
[2023-01-04 12:33:44,074] {taskinstance.py:1569} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=populate_crypto_values
AIRFLOW_CTX_TASK_ID=get_crypto_values
AIRFLOW_CTX_EXECUTION_DATE=2021-12-14T07:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2021-12-14T07:00:00+00:00
[2023-01-04 12:33:44,175] {logging_mixin.py:115} INFO - Attempt 1 to get the crypto values has failed. The api status was 429
[2023-01-04 12:33:44,176] {logging_mixin.py:115} INFO - The api response was {"status":{"error_code":429,"error_message":"You've exceeded the Rate Limit. Please visit https://www.coingecko.com/en/api/pricing to subscribe to our API plans for higher rate limits."}}
[2023-01-04 12:33:59,297] {logging_mixin.py:115} INFO - Attempt 2 to get the crypto values has failed. The api status was 429
[2023-01-04 12:33:59,298] {logging_mixin.py:115} INFO - The api response was {"status":{"error_code":429,"error_message":"You've exceeded the Rate Limit. Please visit https://www.coingecko.com/en/api/pricing to subscribe to our API plans for higher rate limits."}}
[2023-01-04 12:34:14,440] {logging_mixin.py:115} INFO - Attempt 3 to get the crypto values has failed. The api status was 429
[2023-01-04 12:34:14,440] {logging_mixin.py:115} INFO - The api response was {"status":{"error_code":429,"error_message":"You've exceeded the Rate Limit. Please visit https://www.coingecko.com/en/api/pricing to subscribe to our API plans for higher rate limits."}}
[2023-01-04 12:34:29,579] {logging_mixin.py:115} INFO - Attempt 4 to get the crypto values has failed. The api status was 429
[2023-01-04 12:34:29,580] {logging_mixin.py:115} INFO - The api response was {"status":{"error_code":429,"error_message":"You've exceeded the Rate Limit. Please visit https://www.coingecko.com/en/api/pricing to subscribe to our API plans for higher rate limits."}}
[2023-01-04 12:34:44,684] {logging_mixin.py:115} INFO - Attempt 5 to get the crypto values has failed. The api status was 429
[2023-01-04 12:34:44,685] {logging_mixin.py:115} INFO - The api response was {"status":{"error_code":429,"error_message":"You've exceeded the Rate Limit. Please visit https://www.coingecko.com/en/api/pricing to subscribe to our API plans for higher rate limits."}}
[2023-01-04 12:34:59,792] {logging_mixin.py:115} INFO - Attempt 6 to get the crypto values has failed. The api status was 429
[2023-01-04 12:34:59,793] {logging_mixin.py:115} INFO - The api response was {"status":{"error_code":429,"error_message":"You've exceeded the Rate Limit. Please visit https://www.coingecko.com/en/api/pricing to subscribe to our API plans for higher rate limits."}}
[2023-01-04 12:35:14,930] {logging_mixin.py:115} INFO - Attempt 7 to get the crypto values has failed. The api status was 429
[2023-01-04 12:35:14,930] {logging_mixin.py:115} INFO - The api response was {"status":{"error_code":429,"error_message":"You've exceeded the Rate Limit. Please visit https://www.coingecko.com/en/api/pricing to subscribe to our API plans for higher rate limits."}}
[2023-01-04 12:35:30,063] {logging_mixin.py:115} INFO - Attempt 8 to get the crypto values has failed. The api status was 429
[2023-01-04 12:35:30,063] {logging_mixin.py:115} INFO - The api response was {"status":{"error_code":429,"error_message":"You've exceeded the Rate Limit. Please visit https://www.coingecko.com/en/api/pricing to subscribe to our API plans for higher rate limits."}}
[2023-01-04 12:35:46,095] {logging_mixin.py:115} INFO - New rows have been added.
[2023-01-04 12:35:46,096] {python.py:173} INFO - Done. Returned value was: None
[2023-01-04 12:35:46,117] {taskinstance.py:1395} INFO - Marking task as SUCCESS. dag_id=populate_crypto_values, task_id=get_crypto_values, execution_date=20211214T070000, start_date=20230104T153343, end_date=20230104T153546
[2023-01-04 12:35:46,197] {local_task_job.py:156} INFO - Task exited with return code 0
[2023-01-04 12:35:46,229] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
