[2023-01-04 13:08:01,260] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: populate_crypto_values.get_crypto_values scheduled__2022-04-15T07:00:00+00:00 [queued]>
[2023-01-04 13:08:01,266] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: populate_crypto_values.get_crypto_values scheduled__2022-04-15T07:00:00+00:00 [queued]>
[2023-01-04 13:08:01,266] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2023-01-04 13:08:01,266] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2023-01-04 13:08:01,266] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2023-01-04 13:08:01,294] {taskinstance.py:1377} INFO - Executing <Task(PythonOperator): get_crypto_values> on 2022-04-15 07:00:00+00:00
[2023-01-04 13:08:01,298] {standard_task_runner.py:52} INFO - Started process 27703 to run task
[2023-01-04 13:08:01,303] {standard_task_runner.py:79} INFO - Running: ['airflow', 'tasks', 'run', 'populate_crypto_values', 'get_crypto_values', 'scheduled__2022-04-15T07:00:00+00:00', '--job-id', '530', '--raw', '--subdir', 'DAGS_FOLDER/populate_crypto_values.py', '--cfg-path', '/tmp/tmpd_ekulhe', '--error-file', '/tmp/tmp4dqzvykn']
[2023-01-04 13:08:01,304] {standard_task_runner.py:80} INFO - Job 530: Subtask get_crypto_values
[2023-01-04 13:08:01,353] {task_command.py:370} INFO - Running <TaskInstance: populate_crypto_values.get_crypto_values scheduled__2022-04-15T07:00:00+00:00 [running]> on host xuxon-virtual-machine
[2023-01-04 13:08:01,412] {taskinstance.py:1569} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=populate_crypto_values
AIRFLOW_CTX_TASK_ID=get_crypto_values
AIRFLOW_CTX_EXECUTION_DATE=2022-04-15T07:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-04-15T07:00:00+00:00
[2023-01-04 13:08:01,514] {logging_mixin.py:115} INFO - Attempt 1 to get the crypto values has failed. The api status was 429
[2023-01-04 13:08:01,514] {logging_mixin.py:115} INFO - The api response was {"status":{"error_code":429,"error_message":"You've exceeded the Rate Limit. Please visit https://www.coingecko.com/en/api/pricing to subscribe to our API plans for higher rate limits."}}
[2023-01-04 13:08:16,648] {logging_mixin.py:115} INFO - Attempt 2 to get the crypto values has failed. The api status was 429
[2023-01-04 13:08:16,648] {logging_mixin.py:115} INFO - The api response was {"status":{"error_code":429,"error_message":"You've exceeded the Rate Limit. Please visit https://www.coingecko.com/en/api/pricing to subscribe to our API plans for higher rate limits."}}
[2023-01-04 13:08:31,761] {logging_mixin.py:115} INFO - Attempt 3 to get the crypto values has failed. The api status was 429
[2023-01-04 13:08:31,762] {logging_mixin.py:115} INFO - The api response was {"status":{"error_code":429,"error_message":"You've exceeded the Rate Limit. Please visit https://www.coingecko.com/en/api/pricing to subscribe to our API plans for higher rate limits."}}
[2023-01-04 13:08:46,901] {logging_mixin.py:115} INFO - Attempt 4 to get the crypto values has failed. The api status was 429
[2023-01-04 13:08:46,902] {logging_mixin.py:115} INFO - The api response was {"status":{"error_code":429,"error_message":"You've exceeded the Rate Limit. Please visit https://www.coingecko.com/en/api/pricing to subscribe to our API plans for higher rate limits."}}
[2023-01-04 13:09:02,031] {logging_mixin.py:115} INFO - Attempt 5 to get the crypto values has failed. The api status was 429
[2023-01-04 13:09:02,031] {logging_mixin.py:115} INFO - The api response was {"status":{"error_code":429,"error_message":"You've exceeded the Rate Limit. Please visit https://www.coingecko.com/en/api/pricing to subscribe to our API plans for higher rate limits."}}
[2023-01-04 13:09:17,179] {logging_mixin.py:115} INFO - Attempt 6 to get the crypto values has failed. The api status was 429
[2023-01-04 13:09:17,180] {logging_mixin.py:115} INFO - The api response was {"status":{"error_code":429,"error_message":"You've exceeded the Rate Limit. Please visit https://www.coingecko.com/en/api/pricing to subscribe to our API plans for higher rate limits."}}
[2023-01-04 13:09:32,305] {logging_mixin.py:115} INFO - Attempt 7 to get the crypto values has failed. The api status was 429
[2023-01-04 13:09:32,306] {logging_mixin.py:115} INFO - The api response was {"status":{"error_code":429,"error_message":"You've exceeded the Rate Limit. Please visit https://www.coingecko.com/en/api/pricing to subscribe to our API plans for higher rate limits."}}
[2023-01-04 13:09:47,437] {logging_mixin.py:115} INFO - Attempt 8 to get the crypto values has failed. The api status was 429
[2023-01-04 13:09:47,438] {logging_mixin.py:115} INFO - The api response was {"status":{"error_code":429,"error_message":"You've exceeded the Rate Limit. Please visit https://www.coingecko.com/en/api/pricing to subscribe to our API plans for higher rate limits."}}
[2023-01-04 13:10:04,101] {logging_mixin.py:115} INFO - New rows have been added.
[2023-01-04 13:10:04,102] {python.py:173} INFO - Done. Returned value was: None
[2023-01-04 13:10:04,120] {taskinstance.py:1395} INFO - Marking task as SUCCESS. dag_id=populate_crypto_values, task_id=get_crypto_values, execution_date=20220415T070000, start_date=20230104T160801, end_date=20230104T161004
[2023-01-04 13:10:04,155] {local_task_job.py:156} INFO - Task exited with return code 0
[2023-01-04 13:10:04,166] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
