[2023-01-04 05:40:32,903] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: populate_crypto_values.get_crypto_values scheduled__2021-05-05T07:00:00+00:00 [queued]>
[2023-01-04 05:40:32,910] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: populate_crypto_values.get_crypto_values scheduled__2021-05-05T07:00:00+00:00 [queued]>
[2023-01-04 05:40:32,910] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2023-01-04 05:40:32,910] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2023-01-04 05:40:32,910] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2023-01-04 05:40:32,923] {taskinstance.py:1377} INFO - Executing <Task(PythonOperator): get_crypto_values> on 2021-05-05 07:00:00+00:00
[2023-01-04 05:40:32,928] {standard_task_runner.py:52} INFO - Started process 11775 to run task
[2023-01-04 05:40:32,934] {standard_task_runner.py:79} INFO - Running: ['airflow', 'tasks', 'run', 'populate_crypto_values', 'get_crypto_values', 'scheduled__2021-05-05T07:00:00+00:00', '--job-id', '182', '--raw', '--subdir', 'DAGS_FOLDER/populate_crypto_values.py', '--cfg-path', '/tmp/tmpnv0ewcn5', '--error-file', '/tmp/tmpgz2sbbd5']
[2023-01-04 05:40:32,935] {standard_task_runner.py:80} INFO - Job 182: Subtask get_crypto_values
[2023-01-04 05:40:32,994] {task_command.py:370} INFO - Running <TaskInstance: populate_crypto_values.get_crypto_values scheduled__2021-05-05T07:00:00+00:00 [running]> on host xuxon-virtual-machine
[2023-01-04 05:40:33,067] {taskinstance.py:1569} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=populate_crypto_values
AIRFLOW_CTX_TASK_ID=get_crypto_values
AIRFLOW_CTX_EXECUTION_DATE=2021-05-05T07:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2021-05-05T07:00:00+00:00
[2023-01-04 05:40:33,914] {logging_mixin.py:115} INFO - Attempt 1 to get the crypto values has failed. The api status was 429
[2023-01-04 05:40:33,915] {logging_mixin.py:115} INFO - The api response was {"status":{"error_code":429,"error_message":"You've exceeded the Rate Limit. Please visit https://www.coingecko.com/en/api/pricing to subscribe to our API plans for higher rate limits."}}
[2023-01-04 05:40:49,037] {logging_mixin.py:115} INFO - Attempt 2 to get the crypto values has failed. The api status was 429
[2023-01-04 05:40:49,038] {logging_mixin.py:115} INFO - The api response was {"status":{"error_code":429,"error_message":"You've exceeded the Rate Limit. Please visit https://www.coingecko.com/en/api/pricing to subscribe to our API plans for higher rate limits."}}
[2023-01-04 05:41:04,179] {logging_mixin.py:115} INFO - Attempt 3 to get the crypto values has failed. The api status was 429
[2023-01-04 05:41:04,179] {logging_mixin.py:115} INFO - The api response was {"status":{"error_code":429,"error_message":"You've exceeded the Rate Limit. Please visit https://www.coingecko.com/en/api/pricing to subscribe to our API plans for higher rate limits."}}
[2023-01-04 05:41:19,287] {logging_mixin.py:115} INFO - Attempt 4 to get the crypto values has failed. The api status was 429
[2023-01-04 05:41:19,287] {logging_mixin.py:115} INFO - The api response was {"status":{"error_code":429,"error_message":"You've exceeded the Rate Limit. Please visit https://www.coingecko.com/en/api/pricing to subscribe to our API plans for higher rate limits."}}
[2023-01-04 05:41:34,426] {logging_mixin.py:115} INFO - Attempt 5 to get the crypto values has failed. The api status was 429
[2023-01-04 05:41:34,428] {logging_mixin.py:115} INFO - The api response was {"status":{"error_code":429,"error_message":"You've exceeded the Rate Limit. Please visit https://www.coingecko.com/en/api/pricing to subscribe to our API plans for higher rate limits."}}
[2023-01-04 05:41:49,525] {logging_mixin.py:115} INFO - Attempt 6 to get the crypto values has failed. The api status was 429
[2023-01-04 05:41:49,526] {logging_mixin.py:115} INFO - The api response was {"status":{"error_code":429,"error_message":"You've exceeded the Rate Limit. Please visit https://www.coingecko.com/en/api/pricing to subscribe to our API plans for higher rate limits."}}
[2023-01-04 05:42:04,661] {logging_mixin.py:115} INFO - Attempt 7 to get the crypto values has failed. The api status was 429
[2023-01-04 05:42:04,662] {logging_mixin.py:115} INFO - The api response was {"status":{"error_code":429,"error_message":"You've exceeded the Rate Limit. Please visit https://www.coingecko.com/en/api/pricing to subscribe to our API plans for higher rate limits."}}
[2023-01-04 05:42:19,756] {logging_mixin.py:115} INFO - Attempt 8 to get the crypto values has failed. The api status was 429
[2023-01-04 05:42:19,756] {logging_mixin.py:115} INFO - The api response was {"status":{"error_code":429,"error_message":"You've exceeded the Rate Limit. Please visit https://www.coingecko.com/en/api/pricing to subscribe to our API plans for higher rate limits."}}
[2023-01-04 05:42:35,546] {logging_mixin.py:115} INFO - New rows have been added.
[2023-01-04 05:42:35,548] {python.py:173} INFO - Done. Returned value was: None
[2023-01-04 05:42:35,574] {taskinstance.py:1395} INFO - Marking task as SUCCESS. dag_id=populate_crypto_values, task_id=get_crypto_values, execution_date=20210505T070000, start_date=20230104T084032, end_date=20230104T084235
[2023-01-04 05:42:35,621] {local_task_job.py:156} INFO - Task exited with return code 0
[2023-01-04 05:42:35,634] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
