[2023-01-04 13:30:55,594] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: populate_crypto_values.get_crypto_values scheduled__2022-07-22T07:00:00+00:00 [queued]>
[2023-01-04 13:30:55,601] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: populate_crypto_values.get_crypto_values scheduled__2022-07-22T07:00:00+00:00 [queued]>
[2023-01-04 13:30:55,601] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2023-01-04 13:30:55,601] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2023-01-04 13:30:55,601] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2023-01-04 13:30:55,614] {taskinstance.py:1377} INFO - Executing <Task(PythonOperator): get_crypto_values> on 2022-07-22 07:00:00+00:00
[2023-01-04 13:30:55,619] {standard_task_runner.py:52} INFO - Started process 30214 to run task
[2023-01-04 13:30:55,624] {standard_task_runner.py:79} INFO - Running: ['airflow', 'tasks', 'run', 'populate_crypto_values', 'get_crypto_values', 'scheduled__2022-07-22T07:00:00+00:00', '--job-id', '628', '--raw', '--subdir', 'DAGS_FOLDER/populate_crypto_values.py', '--cfg-path', '/tmp/tmpi6z00t3w', '--error-file', '/tmp/tmpy0y0g_bw']
[2023-01-04 13:30:55,625] {standard_task_runner.py:80} INFO - Job 628: Subtask get_crypto_values
[2023-01-04 13:30:55,678] {task_command.py:370} INFO - Running <TaskInstance: populate_crypto_values.get_crypto_values scheduled__2022-07-22T07:00:00+00:00 [running]> on host xuxon-virtual-machine
[2023-01-04 13:30:55,742] {taskinstance.py:1569} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=populate_crypto_values
AIRFLOW_CTX_TASK_ID=get_crypto_values
AIRFLOW_CTX_EXECUTION_DATE=2022-07-22T07:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-07-22T07:00:00+00:00
[2023-01-04 13:30:55,842] {logging_mixin.py:115} INFO - Attempt 1 to get the crypto values has failed. The api status was 429
[2023-01-04 13:30:55,843] {logging_mixin.py:115} INFO - The api response was {"status":{"error_code":429,"error_message":"You've exceeded the Rate Limit. Please visit https://www.coingecko.com/en/api/pricing to subscribe to our API plans for higher rate limits."}}
[2023-01-04 13:31:10,957] {logging_mixin.py:115} INFO - Attempt 2 to get the crypto values has failed. The api status was 429
[2023-01-04 13:31:10,958] {logging_mixin.py:115} INFO - The api response was {"status":{"error_code":429,"error_message":"You've exceeded the Rate Limit. Please visit https://www.coingecko.com/en/api/pricing to subscribe to our API plans for higher rate limits."}}
[2023-01-04 13:31:26,113] {logging_mixin.py:115} INFO - Attempt 3 to get the crypto values has failed. The api status was 429
[2023-01-04 13:31:26,114] {logging_mixin.py:115} INFO - The api response was {"status":{"error_code":429,"error_message":"You've exceeded the Rate Limit. Please visit https://www.coingecko.com/en/api/pricing to subscribe to our API plans for higher rate limits."}}
[2023-01-04 13:31:41,218] {logging_mixin.py:115} INFO - Attempt 4 to get the crypto values has failed. The api status was 429
[2023-01-04 13:31:41,218] {logging_mixin.py:115} INFO - The api response was {"status":{"error_code":429,"error_message":"You've exceeded the Rate Limit. Please visit https://www.coingecko.com/en/api/pricing to subscribe to our API plans for higher rate limits."}}
[2023-01-04 13:31:56,345] {logging_mixin.py:115} INFO - Attempt 5 to get the crypto values has failed. The api status was 429
[2023-01-04 13:31:56,345] {logging_mixin.py:115} INFO - The api response was {"status":{"error_code":429,"error_message":"You've exceeded the Rate Limit. Please visit https://www.coingecko.com/en/api/pricing to subscribe to our API plans for higher rate limits."}}
[2023-01-04 13:32:11,482] {logging_mixin.py:115} INFO - Attempt 6 to get the crypto values has failed. The api status was 429
[2023-01-04 13:32:11,482] {logging_mixin.py:115} INFO - The api response was {"status":{"error_code":429,"error_message":"You've exceeded the Rate Limit. Please visit https://www.coingecko.com/en/api/pricing to subscribe to our API plans for higher rate limits."}}
[2023-01-04 13:32:26,618] {logging_mixin.py:115} INFO - Attempt 7 to get the crypto values has failed. The api status was 429
[2023-01-04 13:32:26,619] {logging_mixin.py:115} INFO - The api response was {"status":{"error_code":429,"error_message":"You've exceeded the Rate Limit. Please visit https://www.coingecko.com/en/api/pricing to subscribe to our API plans for higher rate limits."}}
[2023-01-04 13:32:41,752] {logging_mixin.py:115} INFO - Attempt 8 to get the crypto values has failed. The api status was 429
[2023-01-04 13:32:41,752] {logging_mixin.py:115} INFO - The api response was {"status":{"error_code":429,"error_message":"You've exceeded the Rate Limit. Please visit https://www.coingecko.com/en/api/pricing to subscribe to our API plans for higher rate limits."}}
[2023-01-04 13:32:58,117] {logging_mixin.py:115} INFO - New rows have been added.
[2023-01-04 13:32:58,118] {python.py:173} INFO - Done. Returned value was: None
[2023-01-04 13:32:58,126] {taskinstance.py:1395} INFO - Marking task as SUCCESS. dag_id=populate_crypto_values, task_id=get_crypto_values, execution_date=20220722T070000, start_date=20230104T163055, end_date=20230104T163258
[2023-01-04 13:32:58,192] {local_task_job.py:156} INFO - Task exited with return code 0
[2023-01-04 13:32:58,217] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
