[2023-01-04 12:44:35,574] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: populate_crypto_values.get_crypto_values scheduled__2022-01-18T07:00:00+00:00 [queued]>
[2023-01-04 12:44:35,580] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: populate_crypto_values.get_crypto_values scheduled__2022-01-18T07:00:00+00:00 [queued]>
[2023-01-04 12:44:35,580] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2023-01-04 12:44:35,580] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2023-01-04 12:44:35,580] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2023-01-04 12:44:35,593] {taskinstance.py:1377} INFO - Executing <Task(PythonOperator): get_crypto_values> on 2022-01-18 07:00:00+00:00
[2023-01-04 12:44:35,596] {standard_task_runner.py:52} INFO - Started process 25263 to run task
[2023-01-04 12:44:35,602] {standard_task_runner.py:79} INFO - Running: ['airflow', 'tasks', 'run', 'populate_crypto_values', 'get_crypto_values', 'scheduled__2022-01-18T07:00:00+00:00', '--job-id', '443', '--raw', '--subdir', 'DAGS_FOLDER/populate_crypto_values.py', '--cfg-path', '/tmp/tmpma53usrr', '--error-file', '/tmp/tmpegjc2673']
[2023-01-04 12:44:35,603] {standard_task_runner.py:80} INFO - Job 443: Subtask get_crypto_values
[2023-01-04 12:44:35,651] {task_command.py:370} INFO - Running <TaskInstance: populate_crypto_values.get_crypto_values scheduled__2022-01-18T07:00:00+00:00 [running]> on host xuxon-virtual-machine
[2023-01-04 12:44:35,712] {taskinstance.py:1569} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=populate_crypto_values
AIRFLOW_CTX_TASK_ID=get_crypto_values
AIRFLOW_CTX_EXECUTION_DATE=2022-01-18T07:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-01-18T07:00:00+00:00
[2023-01-04 12:44:35,813] {logging_mixin.py:115} INFO - Attempt 1 to get the crypto values has failed. The api status was 429
[2023-01-04 12:44:35,813] {logging_mixin.py:115} INFO - The api response was {"status":{"error_code":429,"error_message":"You've exceeded the Rate Limit. Please visit https://www.coingecko.com/en/api/pricing to subscribe to our API plans for higher rate limits."}}
[2023-01-04 12:44:50,938] {logging_mixin.py:115} INFO - Attempt 2 to get the crypto values has failed. The api status was 429
[2023-01-04 12:44:50,939] {logging_mixin.py:115} INFO - The api response was {"status":{"error_code":429,"error_message":"You've exceeded the Rate Limit. Please visit https://www.coingecko.com/en/api/pricing to subscribe to our API plans for higher rate limits."}}
[2023-01-04 12:45:06,060] {logging_mixin.py:115} INFO - Attempt 3 to get the crypto values has failed. The api status was 429
[2023-01-04 12:45:06,060] {logging_mixin.py:115} INFO - The api response was {"status":{"error_code":429,"error_message":"You've exceeded the Rate Limit. Please visit https://www.coingecko.com/en/api/pricing to subscribe to our API plans for higher rate limits."}}
[2023-01-04 12:45:21,173] {logging_mixin.py:115} INFO - Attempt 4 to get the crypto values has failed. The api status was 429
[2023-01-04 12:45:21,174] {logging_mixin.py:115} INFO - The api response was {"status":{"error_code":429,"error_message":"You've exceeded the Rate Limit. Please visit https://www.coingecko.com/en/api/pricing to subscribe to our API plans for higher rate limits."}}
[2023-01-04 12:45:36,285] {logging_mixin.py:115} INFO - Attempt 5 to get the crypto values has failed. The api status was 429
[2023-01-04 12:45:36,285] {logging_mixin.py:115} INFO - The api response was {"status":{"error_code":429,"error_message":"You've exceeded the Rate Limit. Please visit https://www.coingecko.com/en/api/pricing to subscribe to our API plans for higher rate limits."}}
[2023-01-04 12:45:51,427] {logging_mixin.py:115} INFO - Attempt 6 to get the crypto values has failed. The api status was 429
[2023-01-04 12:45:51,428] {logging_mixin.py:115} INFO - The api response was {"status":{"error_code":429,"error_message":"You've exceeded the Rate Limit. Please visit https://www.coingecko.com/en/api/pricing to subscribe to our API plans for higher rate limits."}}
[2023-01-04 12:46:06,567] {logging_mixin.py:115} INFO - Attempt 7 to get the crypto values has failed. The api status was 429
[2023-01-04 12:46:06,568] {logging_mixin.py:115} INFO - The api response was {"status":{"error_code":429,"error_message":"You've exceeded the Rate Limit. Please visit https://www.coingecko.com/en/api/pricing to subscribe to our API plans for higher rate limits."}}
[2023-01-04 12:46:21,723] {logging_mixin.py:115} INFO - Attempt 8 to get the crypto values has failed. The api status was 429
[2023-01-04 12:46:21,724] {logging_mixin.py:115} INFO - The api response was {"status":{"error_code":429,"error_message":"You've exceeded the Rate Limit. Please visit https://www.coingecko.com/en/api/pricing to subscribe to our API plans for higher rate limits."}}
[2023-01-04 12:46:38,402] {logging_mixin.py:115} INFO - New rows have been added.
[2023-01-04 12:46:38,402] {python.py:173} INFO - Done. Returned value was: None
[2023-01-04 12:46:38,424] {taskinstance.py:1395} INFO - Marking task as SUCCESS. dag_id=populate_crypto_values, task_id=get_crypto_values, execution_date=20220118T070000, start_date=20230104T154435, end_date=20230104T154638
[2023-01-04 12:46:38,493] {local_task_job.py:156} INFO - Task exited with return code 0
[2023-01-04 12:46:38,525] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
