[2023-01-04 06:07:39,528] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: populate_crypto_values.get_crypto_values scheduled__2021-08-25T07:00:00+00:00 [queued]>
[2023-01-04 06:07:39,534] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: populate_crypto_values.get_crypto_values scheduled__2021-08-25T07:00:00+00:00 [queued]>
[2023-01-04 06:07:39,534] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2023-01-04 06:07:39,534] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2023-01-04 06:07:39,534] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2023-01-04 06:07:39,548] {taskinstance.py:1377} INFO - Executing <Task(PythonOperator): get_crypto_values> on 2021-08-25 07:00:00+00:00
[2023-01-04 06:07:39,552] {standard_task_runner.py:52} INFO - Started process 16862 to run task
[2023-01-04 06:07:39,558] {standard_task_runner.py:79} INFO - Running: ['airflow', 'tasks', 'run', 'populate_crypto_values', 'get_crypto_values', 'scheduled__2021-08-25T07:00:00+00:00', '--job-id', '294', '--raw', '--subdir', 'DAGS_FOLDER/populate_crypto_values.py', '--cfg-path', '/tmp/tmpzs20ocje', '--error-file', '/tmp/tmp84lvcffy']
[2023-01-04 06:07:39,559] {standard_task_runner.py:80} INFO - Job 294: Subtask get_crypto_values
[2023-01-04 06:07:40,100] {task_command.py:370} INFO - Running <TaskInstance: populate_crypto_values.get_crypto_values scheduled__2021-08-25T07:00:00+00:00 [running]> on host xuxon-virtual-machine
[2023-01-04 06:07:40,164] {taskinstance.py:1569} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=populate_crypto_values
AIRFLOW_CTX_TASK_ID=get_crypto_values
AIRFLOW_CTX_EXECUTION_DATE=2021-08-25T07:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2021-08-25T07:00:00+00:00
[2023-01-04 06:07:41,622] {logging_mixin.py:115} INFO - Attempt 1 to get the crypto values has failed. The api status was 429
[2023-01-04 06:07:41,622] {logging_mixin.py:115} INFO - The api response was {"status":{"error_code":429,"error_message":"You've exceeded the Rate Limit. Please visit https://www.coingecko.com/en/api/pricing to subscribe to our API plans for higher rate limits."}}
[2023-01-04 06:07:57,135] {logging_mixin.py:115} INFO - Attempt 2 to get the crypto values has failed. The api status was 429
[2023-01-04 06:07:57,136] {logging_mixin.py:115} INFO - The api response was {"status":{"error_code":429,"error_message":"You've exceeded the Rate Limit. Please visit https://www.coingecko.com/en/api/pricing to subscribe to our API plans for higher rate limits."}}
[2023-01-04 06:08:12,260] {logging_mixin.py:115} INFO - Attempt 3 to get the crypto values has failed. The api status was 429
[2023-01-04 06:08:12,261] {logging_mixin.py:115} INFO - The api response was {"status":{"error_code":429,"error_message":"You've exceeded the Rate Limit. Please visit https://www.coingecko.com/en/api/pricing to subscribe to our API plans for higher rate limits."}}
[2023-01-04 06:08:27,373] {logging_mixin.py:115} INFO - Attempt 4 to get the crypto values has failed. The api status was 429
[2023-01-04 06:08:27,373] {logging_mixin.py:115} INFO - The api response was {"status":{"error_code":429,"error_message":"You've exceeded the Rate Limit. Please visit https://www.coingecko.com/en/api/pricing to subscribe to our API plans for higher rate limits."}}
[2023-01-04 06:08:42,494] {logging_mixin.py:115} INFO - Attempt 5 to get the crypto values has failed. The api status was 429
[2023-01-04 06:08:42,494] {logging_mixin.py:115} INFO - The api response was {"status":{"error_code":429,"error_message":"You've exceeded the Rate Limit. Please visit https://www.coingecko.com/en/api/pricing to subscribe to our API plans for higher rate limits."}}
[2023-01-04 06:08:57,625] {logging_mixin.py:115} INFO - Attempt 6 to get the crypto values has failed. The api status was 429
[2023-01-04 06:08:57,625] {logging_mixin.py:115} INFO - The api response was {"status":{"error_code":429,"error_message":"You've exceeded the Rate Limit. Please visit https://www.coingecko.com/en/api/pricing to subscribe to our API plans for higher rate limits."}}
[2023-01-04 06:09:12,787] {logging_mixin.py:115} INFO - Attempt 7 to get the crypto values has failed. The api status was 429
[2023-01-04 06:09:12,789] {logging_mixin.py:115} INFO - The api response was {"status":{"error_code":429,"error_message":"You've exceeded the Rate Limit. Please visit https://www.coingecko.com/en/api/pricing to subscribe to our API plans for higher rate limits."}}
[2023-01-04 06:09:27,955] {logging_mixin.py:115} INFO - Attempt 8 to get the crypto values has failed. The api status was 429
[2023-01-04 06:09:27,956] {logging_mixin.py:115} INFO - The api response was {"status":{"error_code":429,"error_message":"You've exceeded the Rate Limit. Please visit https://www.coingecko.com/en/api/pricing to subscribe to our API plans for higher rate limits."}}
[2023-01-04 06:09:44,303] {logging_mixin.py:115} INFO - New rows have been added.
[2023-01-04 06:09:44,304] {python.py:173} INFO - Done. Returned value was: None
[2023-01-04 06:09:44,315] {taskinstance.py:1395} INFO - Marking task as SUCCESS. dag_id=populate_crypto_values, task_id=get_crypto_values, execution_date=20210825T070000, start_date=20230104T090739, end_date=20230104T090944
[2023-01-04 06:09:44,381] {local_task_job.py:156} INFO - Task exited with return code 0
[2023-01-04 06:09:44,396] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
