[2023-01-04 12:56:01,480] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: populate_crypto_values.get_crypto_values scheduled__2022-03-07T07:00:00+00:00 [queued]>
[2023-01-04 12:56:01,486] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: populate_crypto_values.get_crypto_values scheduled__2022-03-07T07:00:00+00:00 [queued]>
[2023-01-04 12:56:01,486] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2023-01-04 12:56:01,486] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2023-01-04 12:56:01,486] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2023-01-04 12:56:01,498] {taskinstance.py:1377} INFO - Executing <Task(PythonOperator): get_crypto_values> on 2022-03-07 07:00:00+00:00
[2023-01-04 12:56:01,502] {standard_task_runner.py:52} INFO - Started process 26605 to run task
[2023-01-04 12:56:01,507] {standard_task_runner.py:79} INFO - Running: ['airflow', 'tasks', 'run', 'populate_crypto_values', 'get_crypto_values', 'scheduled__2022-03-07T07:00:00+00:00', '--job-id', '491', '--raw', '--subdir', 'DAGS_FOLDER/populate_crypto_values.py', '--cfg-path', '/tmp/tmpvfkes5ty', '--error-file', '/tmp/tmp5mx0gq5k']
[2023-01-04 12:56:01,508] {standard_task_runner.py:80} INFO - Job 491: Subtask get_crypto_values
[2023-01-04 12:56:01,557] {task_command.py:370} INFO - Running <TaskInstance: populate_crypto_values.get_crypto_values scheduled__2022-03-07T07:00:00+00:00 [running]> on host xuxon-virtual-machine
[2023-01-04 12:56:01,652] {taskinstance.py:1569} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=populate_crypto_values
AIRFLOW_CTX_TASK_ID=get_crypto_values
AIRFLOW_CTX_EXECUTION_DATE=2022-03-07T07:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-03-07T07:00:00+00:00
[2023-01-04 12:56:01,777] {logging_mixin.py:115} INFO - Attempt 1 to get the crypto values has failed. The api status was 429
[2023-01-04 12:56:01,777] {logging_mixin.py:115} INFO - The api response was {"status":{"error_code":429,"error_message":"You've exceeded the Rate Limit. Please visit https://www.coingecko.com/en/api/pricing to subscribe to our API plans for higher rate limits."}}
[2023-01-04 12:56:16,881] {logging_mixin.py:115} INFO - Attempt 2 to get the crypto values has failed. The api status was 429
[2023-01-04 12:56:16,881] {logging_mixin.py:115} INFO - The api response was {"status":{"error_code":429,"error_message":"You've exceeded the Rate Limit. Please visit https://www.coingecko.com/en/api/pricing to subscribe to our API plans for higher rate limits."}}
[2023-01-04 12:56:32,012] {logging_mixin.py:115} INFO - Attempt 3 to get the crypto values has failed. The api status was 429
[2023-01-04 12:56:32,013] {logging_mixin.py:115} INFO - The api response was {"status":{"error_code":429,"error_message":"You've exceeded the Rate Limit. Please visit https://www.coingecko.com/en/api/pricing to subscribe to our API plans for higher rate limits."}}
[2023-01-04 12:56:47,137] {logging_mixin.py:115} INFO - Attempt 4 to get the crypto values has failed. The api status was 429
[2023-01-04 12:56:47,138] {logging_mixin.py:115} INFO - The api response was {"status":{"error_code":429,"error_message":"You've exceeded the Rate Limit. Please visit https://www.coingecko.com/en/api/pricing to subscribe to our API plans for higher rate limits."}}
[2023-01-04 12:57:02,255] {logging_mixin.py:115} INFO - Attempt 5 to get the crypto values has failed. The api status was 429
[2023-01-04 12:57:02,256] {logging_mixin.py:115} INFO - The api response was {"status":{"error_code":429,"error_message":"You've exceeded the Rate Limit. Please visit https://www.coingecko.com/en/api/pricing to subscribe to our API plans for higher rate limits."}}
[2023-01-04 12:57:17,411] {logging_mixin.py:115} INFO - Attempt 6 to get the crypto values has failed. The api status was 429
[2023-01-04 12:57:17,412] {logging_mixin.py:115} INFO - The api response was {"status":{"error_code":429,"error_message":"You've exceeded the Rate Limit. Please visit https://www.coingecko.com/en/api/pricing to subscribe to our API plans for higher rate limits."}}
[2023-01-04 12:57:32,526] {logging_mixin.py:115} INFO - Attempt 7 to get the crypto values has failed. The api status was 429
[2023-01-04 12:57:32,526] {logging_mixin.py:115} INFO - The api response was {"status":{"error_code":429,"error_message":"You've exceeded the Rate Limit. Please visit https://www.coingecko.com/en/api/pricing to subscribe to our API plans for higher rate limits."}}
[2023-01-04 12:57:47,673] {logging_mixin.py:115} INFO - Attempt 8 to get the crypto values has failed. The api status was 429
[2023-01-04 12:57:47,674] {logging_mixin.py:115} INFO - The api response was {"status":{"error_code":429,"error_message":"You've exceeded the Rate Limit. Please visit https://www.coingecko.com/en/api/pricing to subscribe to our API plans for higher rate limits."}}
[2023-01-04 12:58:03,957] {logging_mixin.py:115} INFO - New rows have been added.
[2023-01-04 12:58:03,958] {python.py:173} INFO - Done. Returned value was: None
[2023-01-04 12:58:03,980] {taskinstance.py:1395} INFO - Marking task as SUCCESS. dag_id=populate_crypto_values, task_id=get_crypto_values, execution_date=20220307T070000, start_date=20230104T155601, end_date=20230104T155803
[2023-01-04 12:58:04,040] {local_task_job.py:156} INFO - Task exited with return code 0
[2023-01-04 12:58:04,071] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
